-- ══════════════════════════════════════════════════════════════════════
--  Supabase migration bundle — 0001_foundation.sql through 0017_contact_submissions.sql
--
--  Paste this whole file into the Supabase SQL editor and run it once.
--
--  Generated by scripts/build-migration-bundle.mjs from the migrations in
--  supabase/migrations/. Do not edit this file: edit the migration and
--  regenerate, or the SQL you run in production stops matching the SQL CI
--  tests.
--
--  Run this ONCE, on an empty database. It creates enum types, which
--  Postgres has no `create type if not exists` for — so a second run
--  stops at the first one. That is harmless (the whole thing is in a
--  transaction and rolls back), but it is not a no-op.
--
--  It runs in one transaction: if any statement fails, nothing is applied and
--  you can fix and re-paste.
--
--  This is the complete schema. Run it on a brand-new project.
--
--  Contains:
--    0001_foundation.sql
--    0002_projects.sql
--    0003_billing.sql
--    0004_bookings.sql
--    0005_engagement.sql
--    0006_messaging.sql
--    0007_tidycal.sql
--    0008_client_slugs.sql
--    0009_client_private.sql
--    0010_activity_integrity_and_pitch_views.sql
--    0011_client_preferences.sql
--    0012_analytics.sql
--    0013_nudge_queries.sql
--    0014_billing_event_integrity.sql
--    0015_booking_rules_and_attachments.sql
--    0016_pitch_view_rate_limit.sql
--    0017_contact_submissions.sql
-- ══════════════════════════════════════════════════════════════════════

begin;


-- ══════════════════════════════════════════════════════════════════════
--  0001_foundation.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 1 — Foundation
--  clients · profiles/roles · activity events · audit log
--  Row Level Security is the real access boundary — never trust the client.
-- ════════════════════════════════════════════════════════════════════════

-- ─── Enums ──────────────────────────────────────────────────────────────
create type public.user_role     as enum ('admin', 'client');
create type public.client_status as enum ('active', 'paused', 'churned');
create type public.client_tier   as enum ('project', 'subscription', 'hybrid');

-- ─── clients (admin-managed core record) ────────────────────────────────
create table public.clients (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  company       text,
  email         text not null unique,
  phone         text,
  tier          public.client_tier   not null default 'hybrid',
  status        public.client_status not null default 'active',
  tags          text[]  not null default '{}',
  notes         text,                       -- admin-only, never exposed to client (see RLS)
  custom_fields jsonb   not null default '{}'::jsonb,
  -- per-client module toggles: services on/off without a redeploy
  modules       jsonb   not null default
    '{"projects":true,"billing":true,"bookings":true,"messaging":true}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index clients_status_idx    on public.clients (status);
create index clients_tier_idx      on public.clients (tier);

-- ─── profiles (links auth.users → role + client) ────────────────────────
create table public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  role       public.user_role not null default 'client',
  client_id  uuid references public.clients (id) on delete set null,
  full_name  text,
  created_at timestamptz not null default now()
);

create index profiles_client_id_idx on public.profiles (client_id);

-- ─── activity_events (engagement telemetry — populated from day one) ─────
create table public.activity_events (
  id         uuid primary key default gen_random_uuid(),
  client_id  uuid references public.clients (id) on delete cascade,
  actor_id   uuid references auth.users (id) on delete set null,
  event_type text not null,                 -- login | milestone_approved | message_sent | invoice_paid | booking_made | ...
  metadata   jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index activity_client_time_idx on public.activity_events (client_id, created_at desc);
create index activity_type_idx        on public.activity_events (event_type);

-- ─── audit_log (admin actions on client records — NFR: auditability) ────
create table public.audit_log (
  id         uuid primary key default gen_random_uuid(),
  actor_id   uuid references auth.users (id) on delete set null,
  client_id  uuid references public.clients (id) on delete set null,
  action     text not null,                 -- status_change | note_edit | module_toggle | ...
  detail     jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index audit_client_time_idx on public.audit_log (client_id, created_at desc);

-- ════════════════════════════════════════════════════════════════════════
--  Helper functions (SECURITY DEFINER → bypass RLS to avoid recursion)
-- ════════════════════════════════════════════════════════════════════════
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.current_client_id()
returns uuid
language sql stable security definer set search_path = public
as $$
  select client_id from public.profiles where id = auth.uid();
$$;

-- ════════════════════════════════════════════════════════════════════════
--  Row Level Security
-- ════════════════════════════════════════════════════════════════════════
alter table public.clients         enable row level security;
alter table public.profiles        enable row level security;
alter table public.activity_events enable row level security;
alter table public.audit_log       enable row level security;

-- clients ────────────────────────────────────────────────────────────────
-- Admin: full access. Client: read ONLY their own record.
-- (The client-facing query layer must never select `notes`; RLS still limits
--  the row set, and admin-only columns are excluded at the API layer.)
create policy clients_admin_all on public.clients
  for all using (public.is_admin()) with check (public.is_admin());

create policy clients_client_read_own on public.clients
  for select using (id = public.current_client_id());

-- profiles ───────────────────────────────────────────────────────────────
create policy profiles_admin_all on public.profiles
  for all using (public.is_admin()) with check (public.is_admin());

create policy profiles_read_own on public.profiles
  for select using (id = auth.uid());

-- activity_events ─────────────────────────────────────────────────────────
create policy activity_admin_all on public.activity_events
  for all using (public.is_admin()) with check (public.is_admin());

create policy activity_client_read_own on public.activity_events
  for select using (client_id = public.current_client_id());

-- Any authenticated user may log an event, but only against their own client
-- (or, for admins, any client). event_type/metadata validated at the API layer.
create policy activity_insert_self on public.activity_events
  for insert with check (
    public.is_admin() or client_id = public.current_client_id()
  );

-- audit_log ────────────────────────────────────────────────────────────────
-- Admin-only, and read-only from the app (writes go through log_admin_action).
create policy audit_admin_read on public.audit_log
  for select using (public.is_admin());

-- ════════════════════════════════════════════════════════════════════════
--  Convenience writers
-- ════════════════════════════════════════════════════════════════════════
create or replace function public.log_activity(
  p_event_type text,
  p_client_id  uuid default null,
  p_metadata   jsonb default '{}'::jsonb
)
returns void
language plpgsql security invoker set search_path = public
as $$
begin
  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (coalesce(p_client_id, public.current_client_id()), auth.uid(), p_event_type, p_metadata);
end;
$$;

create or replace function public.log_admin_action(
  p_action    text,
  p_client_id uuid,
  p_detail    jsonb default '{}'::jsonb
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorised';
  end if;
  insert into public.audit_log (actor_id, client_id, action, detail)
  values (auth.uid(), p_client_id, p_action, p_detail);
end;
$$;

-- keep clients.updated_at fresh
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger clients_touch_updated_at
  before update on public.clients
  for each row execute function public.touch_updated_at();


-- ══════════════════════════════════════════════════════════════════════
--  0002_projects.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 2 — Projects
--  projects · milestones, with client view/approve and admin management.
--  Milestone responses and "ready for review" flags emit activity_events so
--  the Phase 5 nudge engine can act on stalled approvals (48h rule).
-- ════════════════════════════════════════════════════════════════════════

create type public.project_status as enum
  ('not_started', 'in_progress', 'review', 'approved', 'complete');

create type public.milestone_status as enum
  ('pending', 'in_progress', 'ready_for_review', 'approved', 'rejected', 'complete');

-- ─── projects ───────────────────────────────────────────────────────────
create table public.projects (
  id          uuid primary key default gen_random_uuid(),
  client_id   uuid not null references public.clients (id) on delete cascade,
  name        text not null,
  description text,
  status      public.project_status not null default 'not_started',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index projects_client_idx on public.projects (client_id, created_at desc);

-- ─── milestones (ordered, per project) ──────────────────────────────────
create table public.milestones (
  id               uuid primary key default gen_random_uuid(),
  project_id       uuid not null references public.projects (id) on delete cascade,
  name             text not null,
  description      text,
  due_date         date,
  position         int  not null default 0,
  status           public.milestone_status not null default 'pending',
  ready_at         timestamptz,             -- when admin flagged "ready for review"
  responded_at     timestamptz,             -- when client approved/rejected
  responded_by     uuid references auth.users (id) on delete set null,
  response_comment text,
  created_at       timestamptz not null default now()
);

create index milestones_project_idx on public.milestones (project_id, position);
create index milestones_ready_idx    on public.milestones (status) where status = 'ready_for_review';

-- keep projects.updated_at fresh
create trigger projects_touch_updated_at
  before update on public.projects
  for each row execute function public.touch_updated_at();

-- ════════════════════════════════════════════════════════════════════════
--  Row Level Security
-- ════════════════════════════════════════════════════════════════════════
alter table public.projects   enable row level security;
alter table public.milestones enable row level security;

-- projects: admin full; client reads only their own
create policy projects_admin_all on public.projects
  for all using (public.is_admin()) with check (public.is_admin());

create policy projects_client_read on public.projects
  for select using (client_id = public.current_client_id());

-- milestones: admin full; client reads milestones of their own projects.
-- Client writes go exclusively through respond_to_milestone() (below), so
-- there is deliberately no client UPDATE policy here.
create policy milestones_admin_all on public.milestones
  for all using (public.is_admin()) with check (public.is_admin());

create policy milestones_client_read on public.milestones
  for select using (
    exists (
      select 1 from public.projects p
      where p.id = milestones.project_id
        and p.client_id = public.current_client_id()
    )
  );

-- ════════════════════════════════════════════════════════════════════════
--  Secure transitions (centralise auth + activity logging)
-- ════════════════════════════════════════════════════════════════════════

-- Admin flags a milestone ready → client sees it, 48h nudge clock starts.
create or replace function public.mark_milestone_ready(p_milestone_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
begin
  if not public.is_admin() then
    raise exception 'not authorised';
  end if;

  select p.client_id into v_client
  from public.milestones m
  join public.projects p on p.id = m.project_id
  where m.id = p_milestone_id;

  if v_client is null then
    raise exception 'milestone not found';
  end if;

  update public.milestones
     set status = 'ready_for_review', ready_at = now()
   where id = p_milestone_id;

  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (v_client, auth.uid(), 'milestone_ready',
          jsonb_build_object('milestone_id', p_milestone_id));
end;
$$;

-- Client (or admin) approves/rejects a milestone that is ready for review.
create or replace function public.respond_to_milestone(
  p_milestone_id uuid,
  p_approve      boolean,
  p_comment      text default null
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
  v_status public.milestone_status;
begin
  select p.client_id, m.status into v_client, v_status
  from public.milestones m
  join public.projects p on p.id = m.project_id
  where m.id = p_milestone_id;

  if v_client is null then
    raise exception 'milestone not found';
  end if;

  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;

  if v_status <> 'ready_for_review' then
    raise exception 'milestone is not awaiting review';
  end if;

  update public.milestones
     set status = case when p_approve then 'approved' else 'rejected' end,
         responded_at = now(),
         responded_by = auth.uid(),
         response_comment = p_comment
   where id = p_milestone_id;

  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (v_client, auth.uid(),
          case when p_approve then 'milestone_approved' else 'milestone_rejected' end,
          jsonb_build_object('milestone_id', p_milestone_id, 'comment', p_comment));
end;
$$;


-- ══════════════════════════════════════════════════════════════════════
--  0003_billing.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 3 — Billing (Stripe)
--  subscriptions + invoices, synced from Stripe via webhook (service role).
--  Amounts are stored in minor units (e.g. pence) as Stripe reports them.
--  Clients read their own rows; writes come only from the webhook.
-- ════════════════════════════════════════════════════════════════════════

-- Stripe customer handle on the client record.
alter table public.clients
  add column if not exists stripe_customer_id text unique;

-- ─── subscriptions (ongoing services) ───────────────────────────────────
create table public.subscriptions (
  id                     uuid primary key default gen_random_uuid(),
  client_id              uuid not null references public.clients (id) on delete cascade,
  stripe_subscription_id text not null unique,
  plan                   text,                 -- price nickname / product name
  status                 text not null,        -- active | trialing | past_due | canceled | ...
  amount                 int,                  -- minor units per period
  currency               text default 'gbp',
  current_period_end     timestamptz,
  cancel_at_period_end   boolean not null default false,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create index subscriptions_client_idx on public.subscriptions (client_id);

-- ─── invoices (one-off project work + subscription charges) ──────────────
create table public.invoices (
  id                 uuid primary key default gen_random_uuid(),
  client_id          uuid not null references public.clients (id) on delete cascade,
  stripe_invoice_id  text not null unique,
  number             text,                     -- human invoice number
  description        text,
  amount             int not null default 0,   -- minor units (total)
  amount_paid        int not null default 0,
  currency           text not null default 'gbp',
  status             text not null,            -- draft | open | paid | uncollectible | void
  due_date           timestamptz,
  paid_at            timestamptz,
  hosted_invoice_url text,                     -- Stripe-hosted pay page
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index invoices_client_time_idx on public.invoices (client_id, created_at desc);
create index invoices_status_idx      on public.invoices (status);

-- keep updated_at fresh
create trigger subscriptions_touch_updated_at
  before update on public.subscriptions
  for each row execute function public.touch_updated_at();

create trigger invoices_touch_updated_at
  before update on public.invoices
  for each row execute function public.touch_updated_at();

-- ════════════════════════════════════════════════════════════════════════
--  Row Level Security  (client reads own; webhook writes via service role)
-- ════════════════════════════════════════════════════════════════════════
alter table public.subscriptions enable row level security;
alter table public.invoices      enable row level security;

create policy subscriptions_admin_all on public.subscriptions
  for all using (public.is_admin()) with check (public.is_admin());
create policy subscriptions_client_read on public.subscriptions
  for select using (client_id = public.current_client_id());

create policy invoices_admin_all on public.invoices
  for all using (public.is_admin()) with check (public.is_admin());
create policy invoices_client_read on public.invoices
  for select using (client_id = public.current_client_id());


-- ══════════════════════════════════════════════════════════════════════
--  0004_bookings.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 4 — Bookings
--  A provider-agnostic bookings table + admin availability windows. The data
--  model is deliberately independent of any scheduler, so an external embed
--  (Cal.com / TidyCal / etc.) can be swapped in later without migration.
--  Status changes emit activity_events; the 24h-unconfirmed admin nudge
--  (Phase 5) keys off requested bookings nearing their start time.
-- ════════════════════════════════════════════════════════════════════════

create type public.booking_status as enum
  ('requested', 'confirmed', 'declined', 'cancelled', 'completed');

-- ─── bookings ───────────────────────────────────────────────────────────
create table public.bookings (
  id             uuid primary key default gen_random_uuid(),
  client_id      uuid not null references public.clients (id) on delete cascade,
  service_type   text not null,
  start_time     timestamptz not null,
  end_time       timestamptz not null,
  status         public.booking_status not null default 'requested',
  notes          text,
  decline_reason text,
  requested_by   uuid references auth.users (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  check (end_time > start_time)
);

create index bookings_client_time_idx on public.bookings (client_id, start_time desc);
create index bookings_pending_idx on public.bookings (status, start_time)
  where status = 'requested';

-- ─── availability_windows (business-wide, recurring weekly) ─────────────
create table public.availability_windows (
  id         uuid primary key default gen_random_uuid(),
  weekday    int  not null check (weekday between 0 and 6), -- 0 = Sunday
  start_time time not null,
  end_time   time not null,
  active     boolean not null default true,
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

create trigger bookings_touch_updated_at
  before update on public.bookings
  for each row execute function public.touch_updated_at();

-- ─── activity logging (all mutation paths) ──────────────────────────────
create or replace function public.log_booking_event()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.activity_events (client_id, actor_id, event_type, metadata)
    values (new.client_id, auth.uid(), 'booking_requested',
            jsonb_build_object('booking_id', new.id, 'start_time', new.start_time));
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    insert into public.activity_events (client_id, actor_id, event_type, metadata)
    values (new.client_id, auth.uid(), 'booking_' || new.status,
            jsonb_build_object('booking_id', new.id, 'start_time', new.start_time));
  end if;
  return new;
end;
$$;

create trigger bookings_log_event
  after insert or update on public.bookings
  for each row execute function public.log_booking_event();

-- ════════════════════════════════════════════════════════════════════════
--  Row Level Security
-- ════════════════════════════════════════════════════════════════════════
alter table public.bookings             enable row level security;
alter table public.availability_windows enable row level security;

-- bookings: admin full; client reads own. Client mutations go through the
-- functions below (no client INSERT/UPDATE policy → status can't be forged).
create policy bookings_admin_all on public.bookings
  for all using (public.is_admin()) with check (public.is_admin());
create policy bookings_client_read on public.bookings
  for select using (client_id = public.current_client_id());

-- availability: everyone signed in can read; only admin writes.
create policy availability_admin_all on public.availability_windows
  for all using (public.is_admin()) with check (public.is_admin());
create policy availability_read on public.availability_windows
  for select using (auth.uid() is not null);

-- ════════════════════════════════════════════════════════════════════════
--  Secure transitions
-- ════════════════════════════════════════════════════════════════════════
create or replace function public.request_booking(
  p_service_type text,
  p_start        timestamptz,
  p_end          timestamptz,
  p_notes        text default null,
  p_client_id    uuid default null
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
  v_id     uuid;
begin
  v_client := coalesce(p_client_id, public.current_client_id());
  if v_client is null then
    raise exception 'no client context';
  end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;
  if p_end <= p_start then
    raise exception 'end must be after start';
  end if;

  insert into public.bookings (client_id, service_type, start_time, end_time, notes, requested_by)
  values (v_client, p_service_type, p_start, p_end, p_notes, auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.reschedule_booking(
  p_id    uuid,
  p_start timestamptz,
  p_end   timestamptz
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
begin
  select client_id into v_client from public.bookings where id = p_id;
  if v_client is null then raise exception 'booking not found'; end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;
  if p_end <= p_start then raise exception 'end must be after start'; end if;

  update public.bookings
     set start_time = p_start, end_time = p_end, status = 'requested', decline_reason = null
   where id = p_id and status in ('requested', 'confirmed');
end;
$$;

create or replace function public.cancel_booking(p_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
begin
  select client_id into v_client from public.bookings where id = p_id;
  if v_client is null then raise exception 'booking not found'; end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;
  update public.bookings set status = 'cancelled'
   where id = p_id and status in ('requested', 'confirmed');
end;
$$;

create or replace function public.confirm_booking(p_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'not authorised'; end if;
  update public.bookings set status = 'confirmed'
   where id = p_id and status = 'requested';
end;
$$;

create or replace function public.decline_booking(p_id uuid, p_reason text default null)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'not authorised'; end if;
  update public.bookings set status = 'declined', decline_reason = p_reason
   where id = p_id and status = 'requested';
end;
$$;


-- ══════════════════════════════════════════════════════════════════════
--  0005_engagement.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 5 — Engagement & Nudges
--  engagement_rules · nudge_log · notifications + a client_engagement view.
--  The evaluator (Vercel Cron → /api/cron/nudges, or the admin "Run now"
--  button) reads activity_events against active rules and enqueues nudges.
-- ════════════════════════════════════════════════════════════════════════

-- ─── engagement_rules (admin-authored, no code) ─────────────────────────
-- condition_type ∈ no_login_days | milestone_awaiting_hours
--                 | invoice_unpaid_days | booking_unconfirmed_hours
create table public.engagement_rules (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  description    text,
  condition_type text not null,
  threshold      int  not null default 0,   -- days or hours per condition_type
  channel        text not null default 'in_app', -- in_app | email | both
  template       text,                        -- message body (supports {{name}})
  active         boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ─── nudge_log (every nudge sent + its outcome) ─────────────────────────
create table public.nudge_log (
  id         uuid primary key default gen_random_uuid(),
  rule_id    uuid references public.engagement_rules (id) on delete set null,
  client_id  uuid references public.clients (id) on delete cascade,
  channel    text not null,
  sent_at    timestamptz not null default now(),
  opened_at  timestamptz,
  clicked_at timestamptz,
  outcome    text not null default 'pending', -- pending | resolved | ignored
  -- prevents re-firing the same rule for the same client within a window
  dedupe_key text unique
);

create index nudge_log_client_time_idx on public.nudge_log (client_id, sent_at desc);
create index nudge_log_rule_idx        on public.nudge_log (rule_id);

-- ─── notifications (in-app bell, both apps) ─────────────────────────────
create table public.notifications (
  id           uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references auth.users (id) on delete cascade,
  type         text not null,             -- nudge | message | system
  payload      jsonb not null default '{}'::jsonb,
  read_at      timestamptz,
  created_at   timestamptz not null default now()
);

create index notifications_recipient_idx on public.notifications (recipient_id, created_at desc);

-- ════════════════════════════════════════════════════════════════════════
--  RLS
-- ════════════════════════════════════════════════════════════════════════
alter table public.engagement_rules enable row level security;
alter table public.nudge_log        enable row level security;
alter table public.notifications    enable row level security;

-- rules + nudge log: admin only. (Writes from the evaluator use service role.)
create policy rules_admin_all on public.engagement_rules
  for all using (public.is_admin()) with check (public.is_admin());
create policy nudge_admin_read on public.nudge_log
  for select using (public.is_admin());

-- notifications: a user sees and updates (mark read) only their own.
create policy notifications_read_own on public.notifications
  for select using (recipient_id = auth.uid());
create policy notifications_update_own on public.notifications
  for update using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());

create trigger rules_touch_updated_at
  before update on public.engagement_rules
  for each row execute function public.touch_updated_at();

-- ════════════════════════════════════════════════════════════════════════
--  client_engagement — simple weighted recency/frequency score (v1)
--  security_invoker so the caller's RLS applies (admin sees all; a client,
--  were they to query it, would see only their own row).
-- ════════════════════════════════════════════════════════════════════════
create view public.client_engagement
with (security_invoker = on) as
select
  c.id                                             as client_id,
  c.name,
  c.status,
  max(e.created_at)                                as last_active,
  count(e.*) filter (where e.created_at > now() - interval '30 days') as events_30d,
  round(
    0.6 * greatest(0, 100 - coalesce(
      extract(day from (now() - max(e.created_at)))::numeric, 60) * 4)
    + 0.4 * least(100, count(e.*) filter
        (where e.created_at > now() - interval '30 days') * 12)
  )::int                                           as score,
  coalesce(max(e.created_at) < now() - interval '14 days', true)
    and c.status = 'active'                        as at_risk
from public.clients c
left join public.activity_events e on e.client_id = c.id
group by c.id, c.name, c.status;

-- ─── notification helper (used by the evaluator + messaging) ────────────
create or replace function public.notify_user(
  p_recipient uuid,
  p_type      text,
  p_payload   jsonb default '{}'::jsonb
)
returns void
language sql security definer set search_path = public
as $$
  insert into public.notifications (recipient_id, type, payload)
  values (p_recipient, p_type, p_payload);
$$;

-- enable Realtime for the bell
alter publication supabase_realtime add table public.notifications;


-- ══════════════════════════════════════════════════════════════════════
--  0006_messaging.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 6 — Messaging
--  Per-client thread between client and admin/team, over Supabase Realtime.
--  File attachments live in a per-client Storage bucket (RLS by path prefix).
-- ════════════════════════════════════════════════════════════════════════

create table public.messages (
  id              uuid primary key default gen_random_uuid(),
  client_id       uuid not null references public.clients (id) on delete cascade,
  sender_id       uuid references auth.users (id) on delete set null,
  sender_is_admin boolean not null default false,
  body            text,
  attachment_path text,
  attachment_name text,
  read_at         timestamptz,
  created_at      timestamptz not null default now(),
  check (body is not null or attachment_path is not null)
);

create index messages_client_time_idx on public.messages (client_id, created_at);
create index messages_unread_idx on public.messages (client_id) where read_at is null;

alter table public.messages enable row level security;

-- admin full; client reads own thread. Sends go through send_message() so
-- sender_is_admin / sender_id can't be forged.
create policy messages_admin_all on public.messages
  for all using (public.is_admin()) with check (public.is_admin());
create policy messages_client_read on public.messages
  for select using (client_id = public.current_client_id());

-- ─── send a message (either side) ───────────────────────────────────────
create or replace function public.send_message(
  p_client_id       uuid,
  p_body            text default null,
  p_attachment_path text default null,
  p_attachment_name text default null
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_admin boolean := public.is_admin();
  v_id    uuid;
  v_uid   uuid;
begin
  if not (v_admin or p_client_id = public.current_client_id()) then
    raise exception 'not authorised';
  end if;
  if p_body is null and p_attachment_path is null then
    raise exception 'empty message';
  end if;

  insert into public.messages
    (client_id, sender_id, sender_is_admin, body, attachment_path, attachment_name)
  values (p_client_id, auth.uid(), v_admin, p_body, p_attachment_path, p_attachment_name)
  returning id into v_id;

  -- log activity + notify the other side
  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (p_client_id, auth.uid(), 'message_sent', jsonb_build_object('message_id', v_id));

  if v_admin then
    -- notify the client's users
    for v_uid in
      select id from public.profiles where client_id = p_client_id and role = 'client'
    loop
      perform public.notify_user(v_uid, 'message',
        jsonb_build_object('message', 'New message from the team',
                           'client_id', p_client_id));
    end loop;
  else
    -- notify all admins
    for v_uid in select id from public.profiles where role = 'admin' loop
      perform public.notify_user(v_uid, 'message',
        jsonb_build_object('message', 'New client message',
                           'client_id', p_client_id));
    end loop;
  end if;

  return v_id;
end;
$$;

-- ─── mark the other side's messages read ────────────────────────────────
create or replace function public.mark_thread_read(p_client_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_admin boolean := public.is_admin();
begin
  if not (v_admin or p_client_id = public.current_client_id()) then
    raise exception 'not authorised';
  end if;
  update public.messages
     set read_at = now()
   where client_id = p_client_id
     and read_at is null
     and sender_is_admin <> v_admin; -- the opposite party's messages
end;
$$;

alter publication supabase_realtime add table public.messages;

-- ════════════════════════════════════════════════════════════════════════
--  Storage — per-client attachments bucket (used by Messaging + Projects)
--  Path convention: <client_id>/<filename>. RLS restricts by first folder.
-- ════════════════════════════════════════════════════════════════════════
insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', false)
on conflict (id) do nothing;

create policy "attachments_read" on storage.objects
  for select to authenticated using (
    bucket_id = 'attachments' and (
      public.is_admin()
      or (storage.foldername(name))[1] = public.current_client_id()::text
    )
  );

create policy "attachments_insert" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'attachments' and (
      public.is_admin()
      or (storage.foldername(name))[1] = public.current_client_id()::text
    )
  );


-- ══════════════════════════════════════════════════════════════════════
--  0007_tidycal.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  TidyCal connector — external booking sync
--  Adds an external reference to bookings so a TidyCal webhook can upsert
--  idempotently. Bookings made in TidyCal land here already confirmed.
-- ════════════════════════════════════════════════════════════════════════

alter table public.bookings
  add column if not exists external_source text,
  add column if not exists external_id     text;

create unique index if not exists bookings_external_uidx
  on public.bookings (external_source, external_id)
  where external_source is not null;


-- ══════════════════════════════════════════════════════════════════════
--  0008_client_slugs.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 8 — Client slugs
--  One slug per client, used as the public identifier for their whole space
--  at /c/<slug>. Replaces the subdomain split (portal.* / clients.*).
--
--  A prospect and a customer are now the same record: you create the client
--  row first, publish a pitch page at /c/<slug>, and when they sign you flip
--  the status and invite them — the URL never changes.
-- ════════════════════════════════════════════════════════════════════════

-- ─── 'prospect' status ──────────────────────────────────────────────────
-- NOTE: Postgres forbids using a new enum value in the same transaction that
-- adds it, so nothing below may reference 'prospect'. It is available to the
-- app from the next statement onwards.
alter type public.client_status add value if not exists 'prospect' before 'active';

-- ─── slugify helper ─────────────────────────────────────────────────────
-- Lowercase, ASCII-ish, hyphen-separated. Used for backfill and available to
-- the admin UI via RPC when suggesting a slug for a new client.
create or replace function public.slugify(p_input text)
returns text
language sql immutable
as $$
  select nullif(
    trim(both '-' from
      regexp_replace(
        regexp_replace(lower(coalesce(p_input, '')), '[^a-z0-9]+', '-', 'g'),
        '-{2,}', '-', 'g'
      )
    ),
    ''
  );
$$;

-- ─── clients.slug ───────────────────────────────────────────────────────
alter table public.clients add column if not exists slug text;

-- Backfill: prefer company, fall back to name, then to a short id fragment.
-- Collisions get a numeric suffix so the unique index below always applies.
do $$
declare
  r          record;
  base       text;
  candidate  text;
  n          int;
begin
  for r in select id, name, company from public.clients where slug is null loop
    base := coalesce(
      public.slugify(r.company),
      public.slugify(r.name),
      'client'
    );
    candidate := base;
    n := 1;
    while exists (select 1 from public.clients where slug = candidate) loop
      n := n + 1;
      candidate := base || '-' || n;
    end loop;
    update public.clients set slug = candidate where id = r.id;
  end loop;
end $$;

alter table public.clients alter column slug set not null;

-- Reserved words would shadow real routes (/c/login, /c/admin, …). The app
-- keeps the same list in lib/routes.ts — change both together.
alter table public.clients
  drop constraint if exists clients_slug_format;
alter table public.clients
  add constraint clients_slug_format check (
    slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    and length(slug) between 2 and 48
    and slug not in ('admin', 'api', 'auth', 'login', 'logout', 'studio',
                     'portal', 'work', 'new', 'settings', 'reset-password',
                     'set-password', 'sitemap', 'robots')
  );

create unique index if not exists clients_slug_key on public.clients (slug);

-- ─── client_pages (public pitch content, 1:1 with clients) ──────────────
-- Deliberately a separate table from `clients`: the client row carries email,
-- notes and billing ids that anonymous visitors must never see. This table
-- holds only what is safe to render on a public pitch page, so the anon read
-- policy below can't leak anything else.
create table if not exists public.client_pages (
  client_id     uuid primary key references public.clients (id) on delete cascade,
  display_name  text not null,                       -- shown as "Prepared for …"
  headline      text,
  note          text not null default '',            -- the personal message
  case_studies  text[] not null default '{}',        -- slugs from lib/client-content.ts
  services      text[] not null default '{}',
  published     boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists client_pages_published_idx
  on public.client_pages (published);

create trigger client_pages_touch_updated_at
  before update on public.client_pages
  for each row execute function public.touch_updated_at();

alter table public.client_pages enable row level security;

-- Admin: full control. Owning client: read their own page even unpublished.
create policy client_pages_admin_all on public.client_pages
  for all using (public.is_admin()) with check (public.is_admin());

create policy client_pages_client_read_own on public.client_pages
  for select using (client_id = public.current_client_id());

-- Anonymous + any authenticated visitor may read PUBLISHED pages only. This
-- is what makes /c/<slug> shareable with a prospect who has no account.
create policy client_pages_public_read on public.client_pages
  for select using (published = true);

-- ─── slug → page resolution for anonymous visitors ──────────────────────
-- Anonymous users can't select from `clients` (RLS denies it), so resolving
-- "/c/acme" to a page needs a definer function that returns the safe subset.
create or replace function public.get_public_client_page(p_slug text)
returns table (
  slug         text,
  display_name text,
  headline     text,
  note         text,
  case_studies text[],
  services     text[]
)
language sql stable security definer set search_path = public
as $$
  select c.slug, p.display_name, p.headline, p.note, p.case_studies, p.services
  from public.client_pages p
  join public.clients c on c.id = p.client_id
  where c.slug = p_slug and p.published = true;
$$;

grant execute on function public.get_public_client_page(text) to anon, authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0009_client_private.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 9 — Admin-only client fields
--
--  `clients.notes` was commented "admin-only, never exposed to client (see
--  RLS)". It wasn't. RLS is ROW-level: the clients_client_read_own policy
--  grants a client SELECT on their whole row, every column included, and no
--  column privileges were ever revoked. Any signed-in client could read the
--  private notes written about them straight from the public anon key:
--
--      supabase.from('clients').select('notes').single()
--
--  Column-level REVOKE can't fix this on its own, because Supabase gives
--  admins and clients the same Postgres role (`authenticated`) — revoking a
--  column from that role locks the admin console out too. Access here differs
--  per user, not per role, which is what RLS is for.
--
--  So the private fields move to their own table with an admin-only policy.
--  Same shape as client_pages: put data in a table whose entire policy set
--  matches its audience, instead of trying to hide columns inside a table
--  that has a broader one.
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.client_private (
  client_id     uuid primary key references public.clients (id) on delete cascade,
  notes         text,
  tags          text[] not null default '{}',
  custom_fields jsonb  not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Carry the existing values over before the columns disappear.
insert into public.client_private (client_id, notes, tags, custom_fields)
select id, notes, tags, custom_fields
from public.clients
on conflict (client_id) do nothing;

alter table public.clients drop column if exists notes;
alter table public.clients drop column if exists tags;
alter table public.clients drop column if exists custom_fields;

create trigger client_private_touch_updated_at
  before update on public.client_private
  for each row execute function public.touch_updated_at();

alter table public.client_private enable row level security;

-- Admin only. There is deliberately no client-facing policy: a client reading
-- this table gets zero rows, not a filtered row.
create policy client_private_admin_all on public.client_private
  for all using (public.is_admin()) with check (public.is_admin());

-- ─── Every client gets its side tables ──────────────────────────────────
-- Enforced by trigger rather than by the admin action, so the invariant holds
-- however a client row is created (console, SQL, a future import script).
create or replace function public.provision_client_records()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.client_private (client_id)
  values (new.id)
  on conflict (client_id) do nothing;

  insert into public.client_pages (client_id, display_name)
  values (new.id, coalesce(nullif(new.company, ''), new.name))
  on conflict (client_id) do nothing;

  return new;
end;
$$;

create trigger clients_provision_records
  after insert on public.clients
  for each row execute function public.provision_client_records();

-- Backfill for clients that predate this trigger (and 0008's client_pages).
insert into public.client_pages (client_id, display_name)
select c.id, coalesce(nullif(c.company, ''), c.name)
from public.clients c
on conflict (client_id) do nothing;

insert into public.client_private (client_id)
select c.id from public.clients c
on conflict (client_id) do nothing;

-- ─── Slug availability check for the admin UI ───────────────────────────
-- `clients` is admin-readable anyway, but a definer function keeps the check
-- to a boolean rather than requiring a table scan from the form.
create or replace function public.slug_available(p_slug text, p_except uuid default null)
returns boolean
language sql stable security definer set search_path = public
as $$
  select not exists (
    select 1 from public.clients
    where slug = p_slug and (p_except is null or id <> p_except)
  );
$$;

grant execute on function public.slug_available(text, uuid) to authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0010_activity_integrity_and_pitch_views.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 10 — Trustworthy activity events, and pitch view tracking
--
--  Part A closes a data-integrity hole: a client could write arbitrary
--  activity events about themselves, which is exactly the data the engagement
--  score and the nudge engine read.
--
--  Part B adds the signal that was missing on the other side — whether a
--  prospect ever opened the pitch you sent them.
-- ════════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════════
--  Part A — activity_events integrity
--
--  `activity_insert_self` let any signed-in client INSERT straight into
--  activity_events as long as client_id was their own. event_type and
--  metadata were never constrained, so:
--
--      supabase.from('activity_events')
--              .insert({ client_id: mine, event_type: 'milestone_approved' })
--
--  worked from the browser with the public anon key. client_engagement scores
--  on those rows and the nudge evaluator reads them, so a client could keep
--  themselves looking active and suppress the very at-risk nudges meant to
--  tell you they'd gone quiet — backwards from what the signal is for.
--
--  Clients now have no direct INSERT path at all. Everything goes through
--  log_activity(), which validates. The state-transition functions in earlier
--  migrations (respond_to_milestone, send_message, the booking trigger …) are
--  SECURITY DEFINER and write as the owner, so they are unaffected.
-- ════════════════════════════════════════════════════════════════════════

drop policy if exists activity_insert_self on public.activity_events;

-- `activity_admin_all` from 0001 already covers admin insert/select/update.
-- No client-facing INSERT policy is created here on purpose: with RLS on and
-- no policy that permits it, a client insert is denied rather than filtered.

/**
 * The only client-callable way to record activity.
 *
 * SECURITY DEFINER because clients no longer hold INSERT on the table — the
 * validation below is what earns the elevated write, so every branch either
 * proves the caller's claim or refuses.
 */
create or replace function public.log_activity(
  p_event_type text,
  p_client_id  uuid default null,
  p_metadata   jsonb default '{}'::jsonb
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_admin  boolean := public.is_admin();
  v_client uuid;
  v_recent boolean;
begin
  -- Admins may log anything anywhere — that's the ops console and the
  -- evaluator, both already trusted.
  if v_admin then
    insert into public.activity_events (client_id, actor_id, event_type, metadata)
    values (coalesce(p_client_id, public.current_client_id()), auth.uid(), p_event_type, p_metadata);
    return;
  end if;

  v_client := public.current_client_id();
  if v_client is null then
    raise exception 'no client context';
  end if;

  -- A client may only ever write about themselves, whatever they passed.
  if p_client_id is not null and p_client_id <> v_client then
    raise exception 'not authorised';
  end if;

  -- Allowlist. 'login' is the only thing the browser beacon needs; every
  -- meaningful event (milestone_approved, invoice_paid, booking_confirmed …)
  -- is emitted by a definer function that has already checked the state
  -- change actually happened.
  if p_event_type <> 'login' then
    raise exception 'event_type % is not client-loggable', p_event_type;
  end if;

  -- Rate limit: sessionStorage in the beacon is client-side and trivially
  -- cleared, so without this a client could inflate their own frequency
  -- score by reloading.
  select exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'login'
      and actor_id   = auth.uid()
      and created_at > now() - interval '30 minutes'
  ) into v_recent;

  if v_recent then
    return;
  end if;

  -- Metadata is dropped for client-logged events: nothing reads it, and it
  -- would be an unvalidated jsonb write straight from the browser.
  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (v_client, auth.uid(), 'login', '{}'::jsonb);
end;
$$;

grant execute on function public.log_activity(text, uuid, jsonb) to authenticated;


-- ════════════════════════════════════════════════════════════════════════
--  Part B — pitch views
--
--  You send a prospect /c/{slug} and currently learn nothing. These counters
--  answer the two questions that change what you do next: did they open it,
--  and when did they last look.
--
--  First-party only — a random visitor id in a cookie this app sets. No IP,
--  no user agent, no third-party script.
-- ════════════════════════════════════════════════════════════════════════

alter table public.client_pages
  add column if not exists view_count      integer     not null default 0,
  add column if not exists visitor_count   integer     not null default 0,
  add column if not exists first_viewed_at timestamptz,
  add column if not exists last_viewed_at  timestamptz;

-- Lookups for "have they opened it, and when" per client.
create index if not exists activity_pitch_views_idx
  on public.activity_events (client_id, created_at desc)
  where event_type = 'pitch_viewed';

/**
 * Record that someone opened a published pitch page.
 *
 * Returns true when the view was counted, false when it was throttled or the
 * slug isn't a published page. Definer so an anonymous prospect — who has no
 * session and no write policy anywhere — can still be counted, and so the
 * read-then-write stays a single atomic statement rather than a race between
 * two round trips.
 *
 * Deliberately does NOT accept a count or timestamp from the caller: the only
 * thing the browser supplies is an opaque visitor id.
 */
create or replace function public.record_pitch_view(
  p_slug    text,
  p_visitor text
)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  v_client   uuid;
  v_recent   boolean;
  v_is_new   boolean;
begin
  if p_visitor is null or length(p_visitor) not between 8 and 64 then
    return false;
  end if;

  select c.id into v_client
  from public.clients c
  join public.client_pages p on p.client_id = c.id
  where c.slug = p_slug and p.published = true;

  if v_client is null then
    return false;
  end if;

  -- One view per visitor per 30 minutes, so a refresh isn't a second read.
  select exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'visitor' = p_visitor
      and created_at > now() - interval '30 minutes'
  ) into v_recent;

  if v_recent then
    return false;
  end if;

  -- Has this visitor ever been seen on this page before?
  select not exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'visitor' = p_visitor
  ) into v_is_new;

  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (v_client, null, 'pitch_viewed', jsonb_build_object('visitor', p_visitor));

  update public.client_pages
  set view_count      = view_count + 1,
      visitor_count   = visitor_count + (case when v_is_new then 1 else 0 end),
      first_viewed_at = coalesce(first_viewed_at, now()),
      last_viewed_at  = now()
  where client_id = v_client;

  return true;
end;
$$;

-- Called from a server action, but granted to anon as well: the whole point
-- is counting people who have no account yet.
grant execute on function public.record_pitch_view(text, text) to anon, authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0011_client_preferences.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 11 — Client self-service: preferences and contact details
--
--  Two pages were specified and never built: the client's own settings page,
--  and the admin analytics view. Analytics is a read over tables that already
--  exist. Settings is not: it needs somewhere to put the client's choices,
--  and a way for them to write it.
--
--  A client holds SELECT on their own `clients` row and their own `profiles`
--  row, and UPDATE on neither — deliberately, because those tables carry
--  fields that are the studio's to set (status, tier, modules, role,
--  client_id, stripe_customer_id). The fix is not to widen those policies:
--  an UPDATE policy is row-level like everything else here, so granting a
--  client UPDATE on their `clients` row grants it on every column of that
--  row, including the module toggles they'd be paying for.
--
--  So: preferences live in their own table with a client-scoped policy, and
--  the two fields a client may change about themselves are written by
--  SECURITY DEFINER functions that touch those columns and no others. Same
--  reasoning as client_private and client_pages, one table down.
-- ════════════════════════════════════════════════════════════════════════

-- ─── client_preferences ─────────────────────────────────────────────────
-- One row per client. Every column is a real switch: each one is read by the
-- nudge evaluator before it sends. Nothing here is decorative — a toggle that
-- doesn't change what lands in an inbox is worse than no toggle at all.
create table if not exists public.client_preferences (
  client_id             uuid primary key references public.clients (id) on delete cascade,
  -- "It's been a while" check-ins (no_login_days rules).
  email_reminders       boolean not null default true,
  -- "A milestone is ready for your review" (milestone_awaiting_hours rules).
  email_project_updates boolean not null default true,
  -- "You have an invoice awaiting payment" (invoice_unpaid_days rules).
  email_billing         boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

drop trigger if exists client_preferences_touch_updated_at on public.client_preferences;
create trigger client_preferences_touch_updated_at
  before update on public.client_preferences
  for each row execute function public.touch_updated_at();

alter table public.client_preferences enable row level security;

drop policy if exists client_preferences_admin_all on public.client_preferences;
create policy client_preferences_admin_all on public.client_preferences
  for all using (public.is_admin()) with check (public.is_admin());

-- Read-only for the client: the settings page renders from this, but writes
-- go through update_my_preferences() so there is one place that decides what
-- a client may set.
drop policy if exists client_preferences_client_read_own on public.client_preferences;
create policy client_preferences_client_read_own on public.client_preferences
  for select using (client_id = public.current_client_id());

-- ─── provisioning ───────────────────────────────────────────────────────
-- Extend the 0009 trigger rather than adding a second one, so a client row
-- still gains all of its side tables in a single statement.
create or replace function public.provision_client_records()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.client_private (client_id)
  values (new.id)
  on conflict (client_id) do nothing;

  insert into public.client_pages (client_id, display_name)
  values (new.id, coalesce(nullif(new.company, ''), new.name))
  on conflict (client_id) do nothing;

  insert into public.client_preferences (client_id)
  values (new.id)
  on conflict (client_id) do nothing;

  return new;
end;
$$;

insert into public.client_preferences (client_id)
select c.id from public.clients c
on conflict (client_id) do nothing;

-- ════════════════════════════════════════════════════════════════════════
--  Writers
-- ════════════════════════════════════════════════════════════════════════

/**
 * The two contact fields a client owns: the name they're addressed by in the
 * portal (profiles.full_name) and their phone number (clients.phone).
 *
 * SECURITY DEFINER because clients hold UPDATE on neither table. Naming the
 * columns in the UPDATE is what makes that safe: role, client_id, status,
 * tier, modules and stripe_customer_id are not reachable from here, whatever
 * is passed in.
 *
 * Their email is not settable. It is the unique key on `clients`, the address
 * Supabase Auth signs them in with, and the handle the TidyCal webhook
 * matches bookings by — changing it in one place and not the others silently
 * detaches a client from their own bookings. It's an admin action.
 */
create or replace function public.update_my_profile(
  p_full_name text,
  p_phone     text default null
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_uid    uuid := auth.uid();
  v_client uuid;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  update public.profiles
  set full_name = nullif(btrim(p_full_name), '')
  where id = v_uid;

  -- Admins have no client row; their name is the whole update.
  v_client := public.current_client_id();
  if v_client is not null then
    update public.clients
    set phone = nullif(btrim(p_phone), '')
    where id = v_client;
  end if;
end;
$$;

/**
 * Email preferences. Upserts rather than updates so a client whose row
 * predates this migration (or was somehow never provisioned) can still save,
 * and so the function is the only thing that needs to know the defaults.
 */
create or replace function public.update_my_preferences(
  p_email_reminders       boolean,
  p_email_project_updates boolean,
  p_email_billing         boolean
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid := public.current_client_id();
begin
  if v_client is null then
    raise exception 'no client context';
  end if;

  insert into public.client_preferences as p (
    client_id, email_reminders, email_project_updates, email_billing
  )
  values (
    v_client,
    coalesce(p_email_reminders, true),
    coalesce(p_email_project_updates, true),
    coalesce(p_email_billing, true)
  )
  on conflict (client_id) do update
  set email_reminders       = excluded.email_reminders,
      email_project_updates = excluded.email_project_updates,
      email_billing         = excluded.email_billing;
end;
$$;

grant execute on function public.update_my_profile(text, text) to authenticated;
grant execute on function public.update_my_preferences(boolean, boolean, boolean) to authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0012_analytics.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 12 — Analytics aggregates
--
--  The admin analytics page asks four questions of history: what came in,
--  what people did, which events dominate, and who is worth the most. All
--  four are group-bys, and all four are answered here rather than in the
--  page.
--
--  Not out of purism — out of arithmetic. PostgREST caps a request at 1000
--  rows by default, and `activity_events` is the busiest table in the schema
--  (a login beacon, every pitch open, every message). Summing it in the page
--  would mean either paging through a year of rows or silently charting the
--  first thousand and calling it a trend. The second failure is the dangerous
--  one, because a truncated chart still looks like a chart.
--
--  Bucketing uses date_bin() with the range start as origin, so buckets line
--  up with the window the console asked for rather than with the calendar —
--  "last 30 days" starts 30 days ago, not on the 1st.
--
--  Every function is admin-gated and SECURITY INVOKER: RLS still applies
--  underneath, so even a bug in the guard cannot hand a client someone
--  else's numbers.
-- ════════════════════════════════════════════════════════════════════════

create or replace function public.analytics_assert_admin()
returns void
language plpgsql stable security invoker set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorised';
  end if;
end;
$$;

/**
 * Money per bucket. `collected` is what actually landed (amount_paid on
 * invoices paid inside the bucket); `invoiced` is what was billed in it,
 * whether or not it has been paid. Charting only one of the two makes a slow
 * payer look like a slow month.
 */
create or replace function public.analytics_revenue(
  p_from timestamptz,
  p_step interval
)
returns table (
  bucket      timestamptz,
  collected   bigint,
  invoiced    bigint,
  paid_count  bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  with paid as (
    select date_bin(p_step, i.paid_at, p_from) as b,
           sum(i.amount_paid)::bigint          as collected,
           count(*)::bigint                    as paid_count
    from public.invoices i
    where i.paid_at >= p_from
    group by 1
  ),
  billed as (
    select date_bin(p_step, i.created_at, p_from) as b,
           sum(i.amount)::bigint                  as invoiced
    from public.invoices i
    where i.created_at >= p_from
      and i.status <> 'draft'
      and i.status <> 'void'
    group by 1
  )
  select coalesce(paid.b, billed.b),
         coalesce(paid.collected, 0),
         coalesce(billed.invoiced, 0),
         coalesce(paid.paid_count, 0)
  from paid
  full outer join billed on billed.b = paid.b
  order by 1;
end;
$$;

/**
 * Activity per bucket: raw event volume, and how many distinct clients were
 * behind it. Volume alone can't tell one very busy client from ten quiet
 * ones, and the second is the healthier shape.
 */
create or replace function public.analytics_activity(
  p_from timestamptz,
  p_step interval
)
returns table (
  bucket         timestamptz,
  events         bigint,
  active_clients bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  select date_bin(p_step, a.created_at, p_from),
         count(*)::bigint,
         count(distinct a.client_id)::bigint
  from public.activity_events a
  where a.created_at >= p_from
  group by 1
  order by 1;
end;
$$;

/** What kind of activity it was, busiest first. */
create or replace function public.analytics_event_mix(p_from timestamptz)
returns table (
  event_type text,
  events     bigint,
  clients    bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  select a.event_type,
         count(*)::bigint,
         count(distinct a.client_id)::bigint
  from public.activity_events a
  where a.created_at >= p_from
  group by 1
  order by 2 desc, 1;
end;
$$;

/**
 * How many distinct clients did anything at all inside the window.
 *
 * Its own function because neither of the two obvious shortcuts is right:
 * summing the per-bucket distinct counts counts a weekly visitor once per
 * week, and counting the rows of analytics_top_clients caps the answer at
 * that function's limit.
 */
create or replace function public.analytics_active_clients(p_from timestamptz)
returns bigint
language plpgsql stable security invoker set search_path = public
as $$
declare
  v_count bigint;
begin
  perform public.analytics_assert_admin();

  select count(distinct a.client_id) into v_count
  from public.activity_events a
  where a.created_at >= p_from and a.client_id is not null;

  return coalesce(v_count, 0);
end;
$$;

/**
 * Clients ranked by what they paid inside the window, with their event count
 * alongside. Revenue and engagement in the same row is the point: a client
 * paying well and going quiet is the one to call.
 */
create or replace function public.analytics_top_clients(
  p_from  timestamptz,
  p_limit int default 10
)
returns table (
  client_id uuid,
  name      text,
  slug      text,
  collected bigint,
  events    bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  select c.id,
         coalesce(nullif(c.company, ''), c.name),
         c.slug,
         coalesce(rev.collected, 0),
         coalesce(act.events, 0)
  from public.clients c
  left join (
    select i.client_id, sum(i.amount_paid)::bigint as collected
    from public.invoices i
    where i.paid_at >= p_from
    group by 1
  ) rev on rev.client_id = c.id
  left join (
    select a.client_id, count(*)::bigint as events
    from public.activity_events a
    where a.created_at >= p_from
    group by 1
  ) act on act.client_id = c.id
  where coalesce(rev.collected, 0) > 0 or coalesce(act.events, 0) > 0
  order by coalesce(rev.collected, 0) desc, coalesce(act.events, 0) desc
  limit greatest(1, least(p_limit, 50));
end;
$$;

grant execute on function public.analytics_revenue(timestamptz, interval)  to authenticated;
grant execute on function public.analytics_activity(timestamptz, interval) to authenticated;
grant execute on function public.analytics_event_mix(timestamptz)          to authenticated;
grant execute on function public.analytics_active_clients(timestamptz)     to authenticated;
grant execute on function public.analytics_top_clients(timestamptz, int)   to authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0013_nudge_queries.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 13 — Stop the nudge evaluator asking one question per client
--
--  evalNoLogin() fetched every active client and then issued a separate
--  "when did this one last log in" query for each of them. At ten clients
--  that is eleven round trips an hour; at two hundred it is two hundred and
--  one, and the hourly cron starts overlapping itself.
--
--  The obvious fix in TypeScript — pull all recent login events and filter
--  in memory — trades one bug for another: PostgREST caps a response at
--  1000 rows by default, and `activity_events` is the busiest table in the
--  schema. Past that cap the evaluator would quietly start nudging clients
--  who had in fact logged in.
--
--  So the question gets asked once, where the rows are.
-- ════════════════════════════════════════════════════════════════════════

/**
 * Active clients with no `login` event since p_cutoff — exactly the set the
 * no_login_days rule wants to nudge.
 *
 * SECURITY DEFINER and admin-gated: the evaluator runs under the service
 * role, but nothing stops a signed-in client calling an RPC, and the answer
 * is a list of every client who has gone quiet.
 */
create or replace function public.clients_idle_since(p_cutoff timestamptz)
returns table (id uuid, name text, email text)
language plpgsql stable security definer set search_path = public
as $$
begin
  -- The evaluator runs as the service role, which has no auth.uid(). Any
  -- other caller has a session, and must be an admin. `anon` is not granted
  -- EXECUTE at all.
  if auth.uid() is not null and not public.is_admin() then
    raise exception 'not authorised';
  end if;

  return query
  select c.id, c.name, c.email
  from public.clients c
  where c.status = 'active'
    and not exists (
      select 1
      from public.activity_events a
      where a.client_id = c.id
        and a.event_type = 'login'
        and a.created_at > p_cutoff
    );
end;
$$;

-- Makes the NOT EXISTS an index lookup per client rather than a scan.
create index if not exists activity_login_idx
  on public.activity_events (client_id, created_at desc)
  where event_type = 'login';

revoke all on function public.clients_idle_since(timestamptz) from public;
grant execute on function public.clients_idle_since(timestamptz) to authenticated, service_role;


-- ══════════════════════════════════════════════════════════════════════
--  0014_billing_event_integrity.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 14 — Make the Stripe webhook idempotent and order-independent
--
--  Two defects, both in app/api/stripe/webhook/route.ts.
--
--  A. One payment wrote several `invoice_paid` activity events.
--     Eight invoice event types all route to the same sync function, which
--     ends with `if (inv.status === 'paid') insert into activity_events`.
--     Stripe sends both `invoice.paid` and `invoice.payment_succeeded` for a
--     single payment, any later `invoice.updated` on a paid invoice makes a
--     third, and Stripe retries deliveries on top of that.
--
--     `client_engagement` scores on those rows and the nudge evaluator reads
--     them, so paying an invoice inflated a client's engagement several-fold
--     and suppressed the very at-risk nudge meant to flag them going quiet.
--     That is the failure 0010 closed when a *client* forged events; this one
--     the webhook did to itself.
--
--  B. Stripe does not guarantee delivery order. An `invoice.updated` arriving
--     after `invoice.paid` overwrote the row with the older state, so an
--     invoice could read `open` after it had been paid.
-- ════════════════════════════════════════════════════════════════════════

-- ─── A. One invoice_paid per invoice ────────────────────────────────────

-- Clear the duplicates already recorded, keeping the earliest of each set.
delete from public.activity_events a
using public.activity_events b
where a.event_type = 'invoice_paid'
  and b.event_type = 'invoice_paid'
  and a.client_id is not distinct from b.client_id
  and a.metadata->>'stripe_invoice_id' is not null
  and a.metadata->>'stripe_invoice_id' = b.metadata->>'stripe_invoice_id'
  and (a.created_at, a.id) > (b.created_at, b.id);

-- Enforced by the database, not by the handler: two webhook deliveries can
-- race, and a check-then-insert in application code would still let both
-- through. Rows without a stripe id (none today) stay unconstrained, since
-- NULLs are distinct in a unique index.
create unique index if not exists activity_invoice_paid_once
  on public.activity_events (client_id, (metadata->>'stripe_invoice_id'))
  where event_type = 'invoice_paid';

/**
 * The only way the webhook records a payment.
 *
 * SECURITY DEFINER so the conflict target — a partial index — can be spelled
 * out properly, which PostgREST's `on_conflict` cannot express from the
 * client side.
 */
create or replace function public.log_invoice_paid(
  p_client_id          uuid,
  p_stripe_invoice_id  text,
  p_amount             int
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.activity_events (client_id, event_type, metadata)
  values (
    p_client_id,
    'invoice_paid',
    jsonb_build_object('stripe_invoice_id', p_stripe_invoice_id, 'amount', p_amount)
  )
  on conflict (client_id, (metadata->>'stripe_invoice_id'))
    where event_type = 'invoice_paid'
  do nothing;
end;
$$;

revoke all on function public.log_invoice_paid(uuid, text, int) from public;
grant execute on function public.log_invoice_paid(uuid, text, int) to service_role;

-- ─── B. Ignore events that arrive out of order ──────────────────────────

alter table public.invoices
  add column if not exists last_event_at timestamptz;
alter table public.subscriptions
  add column if not exists last_event_at timestamptz;

/**
 * Upsert an invoice, unless a newer Stripe event has already been applied.
 *
 * `p_event_at` is the webhook event's own `created` timestamp — the only
 * ordering Stripe actually gives us. A delivery older than the last one
 * applied is dropped rather than allowed to regress the row.
 */
create or replace function public.sync_stripe_invoice(
  p_client_id  uuid,
  p_stripe_id  text,
  p_event_at   timestamptz,
  p_fields     jsonb
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.invoices (
    client_id, stripe_invoice_id, number, description, amount, amount_paid,
    currency, status, due_date, paid_at, hosted_invoice_url, last_event_at
  )
  values (
    p_client_id,
    p_stripe_id,
    nullif(p_fields->>'number', ''),
    nullif(p_fields->>'description', ''),
    coalesce((p_fields->>'amount')::int, 0),
    coalesce((p_fields->>'amount_paid')::int, 0),
    coalesce(nullif(p_fields->>'currency', ''), 'gbp'),
    coalesce(nullif(p_fields->>'status', ''), 'open'),
    (p_fields->>'due_date')::timestamptz,
    (p_fields->>'paid_at')::timestamptz,
    nullif(p_fields->>'hosted_invoice_url', ''),
    p_event_at
  )
  on conflict (stripe_invoice_id) do update
  set number             = excluded.number,
      description        = excluded.description,
      amount             = excluded.amount,
      amount_paid        = excluded.amount_paid,
      currency           = excluded.currency,
      status             = excluded.status,
      due_date           = excluded.due_date,
      paid_at            = excluded.paid_at,
      hosted_invoice_url = excluded.hosted_invoice_url,
      last_event_at      = excluded.last_event_at
  where public.invoices.last_event_at is null
     or excluded.last_event_at is null
     or excluded.last_event_at >= public.invoices.last_event_at;
end;
$$;

/** As above, for subscriptions. */
create or replace function public.sync_stripe_subscription(
  p_client_id  uuid,
  p_stripe_id  text,
  p_event_at   timestamptz,
  p_fields     jsonb
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.subscriptions (
    client_id, stripe_subscription_id, plan, status, amount, currency,
    current_period_end, cancel_at_period_end, last_event_at
  )
  values (
    p_client_id,
    p_stripe_id,
    nullif(p_fields->>'plan', ''),
    coalesce(nullif(p_fields->>'status', ''), 'active'),
    (p_fields->>'amount')::int,
    coalesce(nullif(p_fields->>'currency', ''), 'gbp'),
    (p_fields->>'current_period_end')::timestamptz,
    coalesce((p_fields->>'cancel_at_period_end')::boolean, false),
    p_event_at
  )
  on conflict (stripe_subscription_id) do update
  set plan                 = excluded.plan,
      status               = excluded.status,
      amount               = excluded.amount,
      currency             = excluded.currency,
      current_period_end   = excluded.current_period_end,
      cancel_at_period_end = excluded.cancel_at_period_end,
      last_event_at        = excluded.last_event_at
  where public.subscriptions.last_event_at is null
     or excluded.last_event_at is null
     or excluded.last_event_at >= public.subscriptions.last_event_at;
end;
$$;

revoke all on function public.sync_stripe_invoice(uuid, text, timestamptz, jsonb) from public;
revoke all on function public.sync_stripe_subscription(uuid, text, timestamptz, jsonb) from public;
grant execute on function public.sync_stripe_invoice(uuid, text, timestamptz, jsonb) to service_role;
grant execute on function public.sync_stripe_subscription(uuid, text, timestamptz, jsonb) to service_role;


-- ══════════════════════════════════════════════════════════════════════
--  0015_booking_rules_and_attachments.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 15 — Booking rules, and limits on the attachments bucket
--
--  `request_booking` validated exactly one thing: that the end was after the
--  start. So a client could book last Tuesday, book 3am on a Sunday, or take
--  a slot another client already held. The availability windows an admin
--  sets in /admin/settings were decorative — nothing ever read them.
--
--  The attachments bucket had no size limit, no type restriction, and no
--  DELETE policy: a file could never be removed, by anyone, including an
--  admin.
-- ════════════════════════════════════════════════════════════════════════

-- ─── Booking validation ─────────────────────────────────────────────────

/**
 * Shared by request and reschedule.
 *
 * TIME ZONE: `availability_windows` stores a bare `time` with no zone, and
 * bookings are `timestamptz`, so the comparison has to pick one. It uses UTC.
 * If the studio ever operates from a zone with daylight saving, the windows
 * shift by an hour against local time twice a year — the fix then is a zone
 * column on the window, not arithmetic here.
 *
 * Admins are exempt from all of it: the console is for fixing things, which
 * includes recording a session that happened yesterday or falls outside the
 * published hours.
 */
create or replace function public.assert_bookable(
  p_start   timestamptz,
  p_end     timestamptz,
  p_exclude uuid default null
)
returns void
language plpgsql stable security definer set search_path = public
as $$
declare
  v_weekday int;
  v_from    time;
  v_to      time;
begin
  if p_end <= p_start then
    raise exception 'end must be after start';
  end if;

  if public.is_admin() then
    return;
  end if;

  if p_start < now() then
    raise exception 'that time has already passed';
  end if;

  -- Availability, but only once some has been published. With no windows
  -- configured the admin UI tells you clients can request any time, and this
  -- keeps that promise.
  if exists (select 1 from public.availability_windows where active) then
    v_weekday := extract(dow from (p_start at time zone 'UTC'))::int;
    v_from    := (p_start at time zone 'UTC')::time;
    v_to      := (p_end   at time zone 'UTC')::time;

    -- A window cannot span midnight (end_time > start_time is CHECKed), so a
    -- booking that wraps past midnight can never sit inside one.
    if (p_end at time zone 'UTC')::date <> (p_start at time zone 'UTC')::date
       or not exists (
         select 1 from public.availability_windows w
         where w.active
           and w.weekday = v_weekday
           and w.start_time <= v_from
           and w.end_time   >= v_to
       )
    then
      raise exception 'that time is outside the available hours';
    end if;
  end if;

  -- One studio, one person: a slot already spoken for is not available, even
  -- if the holder is still only `requested`.
  if exists (
    select 1 from public.bookings b
    where b.status in ('requested', 'confirmed')
      and (p_exclude is null or b.id <> p_exclude)
      and b.start_time < p_end
      and b.end_time   > p_start
  ) then
    raise exception 'that slot is already taken';
  end if;
end;
$$;

grant execute on function public.assert_bookable(timestamptz, timestamptz, uuid) to authenticated;

create or replace function public.request_booking(
  p_service_type text,
  p_start        timestamptz,
  p_end          timestamptz,
  p_notes        text default null,
  p_client_id    uuid default null
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
  v_id     uuid;
begin
  v_client := coalesce(p_client_id, public.current_client_id());
  if v_client is null then
    raise exception 'no client context';
  end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;

  perform public.assert_bookable(p_start, p_end);

  insert into public.bookings (client_id, service_type, start_time, end_time, notes, requested_by)
  values (v_client, p_service_type, p_start, p_end, p_notes, auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.reschedule_booking(
  p_id    uuid,
  p_start timestamptz,
  p_end   timestamptz
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
begin
  select client_id into v_client from public.bookings where id = p_id;
  if v_client is null then raise exception 'booking not found'; end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;

  -- Excluded from the overlap check, or moving a booking by ten minutes
  -- would collide with itself.
  perform public.assert_bookable(p_start, p_end, p_id);

  update public.bookings
     set start_time = p_start, end_time = p_end, status = 'requested', decline_reason = null
   where id = p_id and status in ('requested', 'confirmed');
end;
$$;

-- ─── Attachments bucket ─────────────────────────────────────────────────

-- 25 MB, and formats that belong in a client thread. Enforced by storage
-- itself, so it holds however the upload is issued — the browser check in
-- MessageThread is only there to fail politely before the bytes go up.
update storage.buckets
set file_size_limit = 26214400,
    allowed_mime_types = array[
      'image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/svg+xml',
      'application/pdf',
      'text/plain', 'text/csv', 'text/markdown',
      'application/zip',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    ]
where id = 'attachments';

-- 0006 granted SELECT and INSERT and stopped there, so nothing could ever be
-- removed — not a client who attached the wrong file, not an admin, not a
-- cleanup job. Same folder-scoping as the other two.
drop policy if exists "attachments_delete" on storage.objects;
create policy "attachments_delete" on storage.objects
  for delete to authenticated using (
    bucket_id = 'attachments' and (
      public.is_admin()
      or (storage.foldername(name))[1] = public.current_client_id()::text
    )
  );


-- ══════════════════════════════════════════════════════════════════════
--  0016_pitch_view_rate_limit.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 12 — Rate limiting on pitch views
--
--  record_pitch_view() throttles per visitor id, and the visitor id lives in
--  a cookie. That answers "did this person refresh?" but not "is this one
--  person pretending to be a hundred?" — a caller who discards the cookie
--  between requests gets a fresh id each time, and every one of them counts
--  as a new visitor, writes an activity_events row, and moves the number the
--  admin console reports.
--
--  The fix is a second identity the caller doesn't choose: the server passes
--  an opaque fingerprint (an HMAC of the client IP — see
--  lib/os/actions/pitch-view.ts; the raw address is never sent or stored)
--  and a page will accept only so many distinct visitors from one
--  fingerprint per day. Over the cap the view is still recorded as a repeat
--  view, so a genuinely shared office NAT keeps working; it just stops
--  minting new "visitors".
-- ════════════════════════════════════════════════════════════════════════

-- Distinct-visitor budget per fingerprint, per page, per day.
create or replace function public.pitch_view_visitor_cap()
returns int language sql immutable as $$ select 8 $$;

create index if not exists activity_events_pitch_fingerprint_idx
  on public.activity_events (client_id, ((metadata->>'fp')), created_at desc)
  where event_type = 'pitch_viewed';

drop function if exists public.record_pitch_view(text, text);

create or replace function public.record_pitch_view(
  p_slug        text,
  p_visitor     text,
  p_fingerprint text default null
)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  v_client       uuid;
  v_recent       boolean;
  v_is_new       boolean;
  v_fp_visitors  int := 0;
begin
  if p_visitor is null or length(p_visitor) not between 8 and 64 then
    return false;
  end if;

  -- The fingerprint is minted server-side and is always a fixed-width hex
  -- digest. Anything else is a caller trying its luck; drop it rather than
  -- letting an arbitrary string become a rate-limit bucket of its own.
  if p_fingerprint is not null
     and p_fingerprint !~ '^[0-9a-f]{32}$' then
    p_fingerprint := null;
  end if;

  select c.id into v_client
  from public.clients c
  join public.client_pages p on p.client_id = c.id
  where c.slug = p_slug and p.published = true;

  if v_client is null then
    return false;
  end if;

  -- One view per visitor per 30 minutes, so a refresh isn't a second read.
  select exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'visitor' = p_visitor
      and created_at > now() - interval '30 minutes'
  ) into v_recent;

  if v_recent then
    return false;
  end if;

  -- Has this visitor ever been seen on this page before?
  select not exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'visitor' = p_visitor
  ) into v_is_new;

  -- How many distinct visitors has this fingerprint already produced today?
  if v_is_new and p_fingerprint is not null then
    select count(distinct metadata->>'visitor')
    into v_fp_visitors
    from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'fp' = p_fingerprint
      and created_at > now() - interval '1 day';

    -- Over budget: record the read, but don't let it mint a new visitor.
    if v_fp_visitors >= public.pitch_view_visitor_cap() then
      v_is_new := false;
    end if;
  end if;

  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (
    v_client,
    null,
    'pitch_viewed',
    jsonb_strip_nulls(
      jsonb_build_object('visitor', p_visitor, 'fp', p_fingerprint)
    )
  );

  update public.client_pages
  set view_count      = view_count + 1,
      visitor_count   = visitor_count + (case when v_is_new then 1 else 0 end),
      first_viewed_at = coalesce(first_viewed_at, now()),
      last_viewed_at  = now()
  where client_id = v_client;

  return true;
end;
$$;

-- Called from a server action, but granted to anon as well: the whole point
-- is counting people who have no account yet.
grant execute on function public.record_pitch_view(text, text, text)
  to anon, authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0017_contact_submissions.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 14 — Durable contact submissions
--
--  The studio contact form posted to Netlify Forms and nowhere else. That
--  made a lead's survival depend entirely on one third party being up at the
--  moment somebody clicked Send: if the POST failed the visitor saw
--  "something went wrong", and the enquiry existed nowhere at all. It also
--  meant the only record of who had asked for what lived in a dashboard
--  outside the app, invisible to /admin.
--
--  Submissions now land here first, through a SECURITY DEFINER function so
--  anonymous visitors never touch the table directly. Netlify Forms stays as
--  the notification channel; this is the record.
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.contact_submissions (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  email        text not null,
  company      text,
  project_type text,
  message      text not null,
  -- Which pitch page or campaign the lead came from (?ref= on the studio URL).
  ref          text,
  -- Set once an admin has dealt with it; drives the unread count in /admin.
  handled_at   timestamptz,
  -- Non-null once this submission has been linked to a client record.
  client_id    uuid references public.clients (id) on delete set null,
  created_at   timestamptz not null default now()
);

create index if not exists contact_submissions_time_idx
  on public.contact_submissions (created_at desc);
create index if not exists contact_submissions_unhandled_idx
  on public.contact_submissions (created_at desc)
  where handled_at is null;

alter table public.contact_submissions enable row level security;

-- Admins only. There is no client-facing read path: a submission is a lead,
-- not something the person who sent it comes back to look at.
-- Drop-then-create, like every other policy in this schema: `create policy`
-- has no `if not exists`, so without this the migration is not re-runnable.
drop policy if exists contact_submissions_admin_all on public.contact_submissions;
create policy contact_submissions_admin_all on public.contact_submissions
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

/**
 * Record one submission. Anonymous by design — the whole point is capturing
 * people who have no account.
 *
 * Everything is length-capped here rather than trusted from the caller: this
 * is a public write path, and the only thing standing between it and the
 * table is this function. Returns false rather than raising on bad input, so
 * a malformed post is a quiet no-op instead of a 500 on the contact page.
 */
create or replace function public.submit_contact(
  p_name         text,
  p_email        text,
  p_message      text,
  p_company      text default null,
  p_project_type text default null,
  p_ref          text default null
)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  v_recent int;
begin
  if coalesce(trim(p_name), '') = ''
     or coalesce(trim(p_message), '') = ''
     or p_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    return false;
  end if;

  -- A public insert endpoint needs a ceiling. Same address, same hour: five.
  select count(*) into v_recent
  from public.contact_submissions
  where lower(email) = lower(trim(p_email))
    and created_at > now() - interval '1 hour';

  if v_recent >= 5 then
    return false;
  end if;

  insert into public.contact_submissions
    (name, email, company, project_type, message, ref)
  values (
    left(trim(p_name), 120),
    lower(left(trim(p_email), 200)),
    nullif(left(trim(coalesce(p_company, '')), 160), ''),
    nullif(left(trim(coalesce(p_project_type, '')), 80), ''),
    left(trim(p_message), 5000),
    nullif(left(trim(coalesce(p_ref, '')), 80), '')
  );

  return true;
end;
$$;

grant execute on function
  public.submit_contact(text, text, text, text, text, text)
  to anon, authenticated;

/** Mark a submission dealt with. Admin-only; RLS on the table enforces it. */
create or replace function public.mark_contact_handled(p_id uuid)
returns boolean
language plpgsql security invoker set search_path = public
as $$
begin
  update public.contact_submissions
  set handled_at = now()
  where id = p_id and handled_at is null;
  return found;
end;
$$;

grant execute on function public.mark_contact_handled(uuid) to authenticated;


commit;

-- ══════════════════════════════════════════════════════════════════════
--  Verification — what this bundle should have left behind.
--  Every row below should read 'ok'.
-- ══════════════════════════════════════════════════════════════════════
select
  'client_preferences table'                                        as object,
  case when to_regclass('public.client_preferences') is not null
       then 'ok' else 'MISSING' end                                 as status
union all select 'preferences row per client',
  case when (select count(*) from public.clients)
          = (select count(*) from public.client_preferences)
       then 'ok' else 'MISMATCH' end
union all select 'invoices.last_event_at column',
  case when exists (select 1 from information_schema.columns
                    where table_schema='public' and table_name='invoices'
                      and column_name='last_event_at')
       then 'ok' else 'MISSING' end
union all select 'one invoice_paid per invoice (unique index)',
  case when exists (select 1 from pg_indexes
                    where schemaname='public' and indexname='activity_invoice_paid_once')
       then 'ok' else 'MISSING' end
union all select 'attachments size + type limits',
  case when exists (select 1 from storage.buckets
                    where id='attachments' and file_size_limit is not null
                      and allowed_mime_types is not null)
       then 'ok' else 'MISSING' end
union all select 'attachments delete policy',
  case when exists (select 1 from pg_policies
                    where schemaname='storage' and tablename='objects'
                      and policyname='attachments_delete')
       then 'ok' else 'MISSING' end
union all select 'functions the app calls',
  case when (select count(*) from pg_proc p
             join pg_namespace n on n.oid = p.pronamespace
             where n.nspname='public' and p.proname in (
               'update_my_profile','update_my_preferences',
               'analytics_revenue','analytics_activity','analytics_event_mix',
               'analytics_top_clients','analytics_active_clients',
               'clients_idle_since','log_invoice_paid',
               'sync_stripe_invoice','sync_stripe_subscription','assert_bookable'
             )) = 12
       then 'ok' else 'MISSING ONE OR MORE' end;
