-- ══════════════════════════════════════════════════════════════════════
--  Supabase migration bundle — 0011_client_preferences.sql through 0017_contact_submissions.sql
--
--  Paste this whole file into the Supabase SQL editor and run it once.
--
--  Generated by scripts/build-migration-bundle.mjs from the migrations in
--  supabase/migrations/. Do not edit this file: edit the migration and
--  regenerate, or the SQL you run in production stops matching the SQL CI
--  tests.
--
--  Safe to re-run. Every statement is guarded (create or replace, if not
--  exists, drop-then-create for triggers and policies), so applying it
--  twice changes nothing the second time.
--
--  It runs in one transaction: if any statement fails, nothing is applied and
--  you can fix and re-paste.
--
--  Assumes migrations 0001 through 0010 are already applied.
--
--  Contains:
--    0011_client_preferences.sql
--    0012_analytics.sql
--    0013_nudge_queries.sql
--    0014_billing_event_integrity.sql
--    0015_booking_rules_and_attachments.sql
--    0016_pitch_view_rate_limit.sql
--    0017_contact_submissions.sql
-- ══════════════════════════════════════════════════════════════════════

begin;


-- ══════════════════════════════════════════════════════════════════════
--  0011_client_preferences.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 11 — Client self-service: preferences and contact details
--
--  Two pages were specified and never built: the client's own settings page,
--  and the admin analytics view. Analytics is a read over tables that already
--  exist. Settings is not: it needs somewhere to put the client's choices,
--  and a way for them to write it.
--
--  A client holds SELECT on their own `clients` row and their own `profiles`
--  row, and UPDATE on neither — deliberately, because those tables carry
--  fields that are the studio's to set (status, tier, modules, role,
--  client_id, stripe_customer_id). The fix is not to widen those policies:
--  an UPDATE policy is row-level like everything else here, so granting a
--  client UPDATE on their `clients` row grants it on every column of that
--  row, including the module toggles they'd be paying for.
--
--  So: preferences live in their own table with a client-scoped policy, and
--  the two fields a client may change about themselves are written by
--  SECURITY DEFINER functions that touch those columns and no others. Same
--  reasoning as client_private and client_pages, one table down.
-- ════════════════════════════════════════════════════════════════════════

-- ─── client_preferences ─────────────────────────────────────────────────
-- One row per client. Every column is a real switch: each one is read by the
-- nudge evaluator before it sends. Nothing here is decorative — a toggle that
-- doesn't change what lands in an inbox is worse than no toggle at all.
create table if not exists public.client_preferences (
  client_id             uuid primary key references public.clients (id) on delete cascade,
  -- "It's been a while" check-ins (no_login_days rules).
  email_reminders       boolean not null default true,
  -- "A milestone is ready for your review" (milestone_awaiting_hours rules).
  email_project_updates boolean not null default true,
  -- "You have an invoice awaiting payment" (invoice_unpaid_days rules).
  email_billing         boolean not null default true,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

drop trigger if exists client_preferences_touch_updated_at on public.client_preferences;
create trigger client_preferences_touch_updated_at
  before update on public.client_preferences
  for each row execute function public.touch_updated_at();

alter table public.client_preferences enable row level security;

drop policy if exists client_preferences_admin_all on public.client_preferences;
create policy client_preferences_admin_all on public.client_preferences
  for all using (public.is_admin()) with check (public.is_admin());

-- Read-only for the client: the settings page renders from this, but writes
-- go through update_my_preferences() so there is one place that decides what
-- a client may set.
drop policy if exists client_preferences_client_read_own on public.client_preferences;
create policy client_preferences_client_read_own on public.client_preferences
  for select using (client_id = public.current_client_id());

-- ─── provisioning ───────────────────────────────────────────────────────
-- Extend the 0009 trigger rather than adding a second one, so a client row
-- still gains all of its side tables in a single statement.
create or replace function public.provision_client_records()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.client_private (client_id)
  values (new.id)
  on conflict (client_id) do nothing;

  insert into public.client_pages (client_id, display_name)
  values (new.id, coalesce(nullif(new.company, ''), new.name))
  on conflict (client_id) do nothing;

  insert into public.client_preferences (client_id)
  values (new.id)
  on conflict (client_id) do nothing;

  return new;
end;
$$;

insert into public.client_preferences (client_id)
select c.id from public.clients c
on conflict (client_id) do nothing;

-- ════════════════════════════════════════════════════════════════════════
--  Writers
-- ════════════════════════════════════════════════════════════════════════

/**
 * The two contact fields a client owns: the name they're addressed by in the
 * portal (profiles.full_name) and their phone number (clients.phone).
 *
 * SECURITY DEFINER because clients hold UPDATE on neither table. Naming the
 * columns in the UPDATE is what makes that safe: role, client_id, status,
 * tier, modules and stripe_customer_id are not reachable from here, whatever
 * is passed in.
 *
 * Their email is not settable. It is the unique key on `clients`, the address
 * Supabase Auth signs them in with, and the handle the TidyCal webhook
 * matches bookings by — changing it in one place and not the others silently
 * detaches a client from their own bookings. It's an admin action.
 */
create or replace function public.update_my_profile(
  p_full_name text,
  p_phone     text default null
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_uid    uuid := auth.uid();
  v_client uuid;
begin
  if v_uid is null then
    raise exception 'not authenticated';
  end if;

  update public.profiles
  set full_name = nullif(btrim(p_full_name), '')
  where id = v_uid;

  -- Admins have no client row; their name is the whole update.
  v_client := public.current_client_id();
  if v_client is not null then
    update public.clients
    set phone = nullif(btrim(p_phone), '')
    where id = v_client;
  end if;
end;
$$;

/**
 * Email preferences. Upserts rather than updates so a client whose row
 * predates this migration (or was somehow never provisioned) can still save,
 * and so the function is the only thing that needs to know the defaults.
 */
create or replace function public.update_my_preferences(
  p_email_reminders       boolean,
  p_email_project_updates boolean,
  p_email_billing         boolean
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid := public.current_client_id();
begin
  if v_client is null then
    raise exception 'no client context';
  end if;

  insert into public.client_preferences as p (
    client_id, email_reminders, email_project_updates, email_billing
  )
  values (
    v_client,
    coalesce(p_email_reminders, true),
    coalesce(p_email_project_updates, true),
    coalesce(p_email_billing, true)
  )
  on conflict (client_id) do update
  set email_reminders       = excluded.email_reminders,
      email_project_updates = excluded.email_project_updates,
      email_billing         = excluded.email_billing;
end;
$$;

grant execute on function public.update_my_profile(text, text) to authenticated;
grant execute on function public.update_my_preferences(boolean, boolean, boolean) to authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0012_analytics.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 12 — Analytics aggregates
--
--  The admin analytics page asks four questions of history: what came in,
--  what people did, which events dominate, and who is worth the most. All
--  four are group-bys, and all four are answered here rather than in the
--  page.
--
--  Not out of purism — out of arithmetic. PostgREST caps a request at 1000
--  rows by default, and `activity_events` is the busiest table in the schema
--  (a login beacon, every pitch open, every message). Summing it in the page
--  would mean either paging through a year of rows or silently charting the
--  first thousand and calling it a trend. The second failure is the dangerous
--  one, because a truncated chart still looks like a chart.
--
--  Bucketing uses date_bin() with the range start as origin, so buckets line
--  up with the window the console asked for rather than with the calendar —
--  "last 30 days" starts 30 days ago, not on the 1st.
--
--  Every function is admin-gated and SECURITY INVOKER: RLS still applies
--  underneath, so even a bug in the guard cannot hand a client someone
--  else's numbers.
-- ════════════════════════════════════════════════════════════════════════

create or replace function public.analytics_assert_admin()
returns void
language plpgsql stable security invoker set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorised';
  end if;
end;
$$;

/**
 * Money per bucket. `collected` is what actually landed (amount_paid on
 * invoices paid inside the bucket); `invoiced` is what was billed in it,
 * whether or not it has been paid. Charting only one of the two makes a slow
 * payer look like a slow month.
 */
create or replace function public.analytics_revenue(
  p_from timestamptz,
  p_step interval
)
returns table (
  bucket      timestamptz,
  collected   bigint,
  invoiced    bigint,
  paid_count  bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  with paid as (
    select date_bin(p_step, i.paid_at, p_from) as b,
           sum(i.amount_paid)::bigint          as collected,
           count(*)::bigint                    as paid_count
    from public.invoices i
    where i.paid_at >= p_from
    group by 1
  ),
  billed as (
    select date_bin(p_step, i.created_at, p_from) as b,
           sum(i.amount)::bigint                  as invoiced
    from public.invoices i
    where i.created_at >= p_from
      and i.status <> 'draft'
      and i.status <> 'void'
    group by 1
  )
  select coalesce(paid.b, billed.b),
         coalesce(paid.collected, 0),
         coalesce(billed.invoiced, 0),
         coalesce(paid.paid_count, 0)
  from paid
  full outer join billed on billed.b = paid.b
  order by 1;
end;
$$;

/**
 * Activity per bucket: raw event volume, and how many distinct clients were
 * behind it. Volume alone can't tell one very busy client from ten quiet
 * ones, and the second is the healthier shape.
 */
create or replace function public.analytics_activity(
  p_from timestamptz,
  p_step interval
)
returns table (
  bucket         timestamptz,
  events         bigint,
  active_clients bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  select date_bin(p_step, a.created_at, p_from),
         count(*)::bigint,
         count(distinct a.client_id)::bigint
  from public.activity_events a
  where a.created_at >= p_from
  group by 1
  order by 1;
end;
$$;

/** What kind of activity it was, busiest first. */
create or replace function public.analytics_event_mix(p_from timestamptz)
returns table (
  event_type text,
  events     bigint,
  clients    bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  select a.event_type,
         count(*)::bigint,
         count(distinct a.client_id)::bigint
  from public.activity_events a
  where a.created_at >= p_from
  group by 1
  order by 2 desc, 1;
end;
$$;

/**
 * How many distinct clients did anything at all inside the window.
 *
 * Its own function because neither of the two obvious shortcuts is right:
 * summing the per-bucket distinct counts counts a weekly visitor once per
 * week, and counting the rows of analytics_top_clients caps the answer at
 * that function's limit.
 */
create or replace function public.analytics_active_clients(p_from timestamptz)
returns bigint
language plpgsql stable security invoker set search_path = public
as $$
declare
  v_count bigint;
begin
  perform public.analytics_assert_admin();

  select count(distinct a.client_id) into v_count
  from public.activity_events a
  where a.created_at >= p_from and a.client_id is not null;

  return coalesce(v_count, 0);
end;
$$;

/**
 * Clients ranked by what they paid inside the window, with their event count
 * alongside. Revenue and engagement in the same row is the point: a client
 * paying well and going quiet is the one to call.
 */
create or replace function public.analytics_top_clients(
  p_from  timestamptz,
  p_limit int default 10
)
returns table (
  client_id uuid,
  name      text,
  slug      text,
  collected bigint,
  events    bigint
)
language plpgsql stable security invoker set search_path = public
as $$
begin
  perform public.analytics_assert_admin();

  return query
  select c.id,
         coalesce(nullif(c.company, ''), c.name),
         c.slug,
         coalesce(rev.collected, 0),
         coalesce(act.events, 0)
  from public.clients c
  left join (
    select i.client_id, sum(i.amount_paid)::bigint as collected
    from public.invoices i
    where i.paid_at >= p_from
    group by 1
  ) rev on rev.client_id = c.id
  left join (
    select a.client_id, count(*)::bigint as events
    from public.activity_events a
    where a.created_at >= p_from
    group by 1
  ) act on act.client_id = c.id
  where coalesce(rev.collected, 0) > 0 or coalesce(act.events, 0) > 0
  order by coalesce(rev.collected, 0) desc, coalesce(act.events, 0) desc
  limit greatest(1, least(p_limit, 50));
end;
$$;

grant execute on function public.analytics_revenue(timestamptz, interval)  to authenticated;
grant execute on function public.analytics_activity(timestamptz, interval) to authenticated;
grant execute on function public.analytics_event_mix(timestamptz)          to authenticated;
grant execute on function public.analytics_active_clients(timestamptz)     to authenticated;
grant execute on function public.analytics_top_clients(timestamptz, int)   to authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0013_nudge_queries.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 13 — Stop the nudge evaluator asking one question per client
--
--  evalNoLogin() fetched every active client and then issued a separate
--  "when did this one last log in" query for each of them. At ten clients
--  that is eleven round trips an hour; at two hundred it is two hundred and
--  one, and the hourly cron starts overlapping itself.
--
--  The obvious fix in TypeScript — pull all recent login events and filter
--  in memory — trades one bug for another: PostgREST caps a response at
--  1000 rows by default, and `activity_events` is the busiest table in the
--  schema. Past that cap the evaluator would quietly start nudging clients
--  who had in fact logged in.
--
--  So the question gets asked once, where the rows are.
-- ════════════════════════════════════════════════════════════════════════

/**
 * Active clients with no `login` event since p_cutoff — exactly the set the
 * no_login_days rule wants to nudge.
 *
 * SECURITY DEFINER and admin-gated: the evaluator runs under the service
 * role, but nothing stops a signed-in client calling an RPC, and the answer
 * is a list of every client who has gone quiet.
 */
create or replace function public.clients_idle_since(p_cutoff timestamptz)
returns table (id uuid, name text, email text)
language plpgsql stable security definer set search_path = public
as $$
begin
  -- The evaluator runs as the service role, which has no auth.uid(). Any
  -- other caller has a session, and must be an admin. `anon` is not granted
  -- EXECUTE at all.
  if auth.uid() is not null and not public.is_admin() then
    raise exception 'not authorised';
  end if;

  return query
  select c.id, c.name, c.email
  from public.clients c
  where c.status = 'active'
    and not exists (
      select 1
      from public.activity_events a
      where a.client_id = c.id
        and a.event_type = 'login'
        and a.created_at > p_cutoff
    );
end;
$$;

-- Makes the NOT EXISTS an index lookup per client rather than a scan.
create index if not exists activity_login_idx
  on public.activity_events (client_id, created_at desc)
  where event_type = 'login';

revoke all on function public.clients_idle_since(timestamptz) from public;
grant execute on function public.clients_idle_since(timestamptz) to authenticated, service_role;


-- ══════════════════════════════════════════════════════════════════════
--  0014_billing_event_integrity.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 14 — Make the Stripe webhook idempotent and order-independent
--
--  Two defects, both in app/api/stripe/webhook/route.ts.
--
--  A. One payment wrote several `invoice_paid` activity events.
--     Eight invoice event types all route to the same sync function, which
--     ends with `if (inv.status === 'paid') insert into activity_events`.
--     Stripe sends both `invoice.paid` and `invoice.payment_succeeded` for a
--     single payment, any later `invoice.updated` on a paid invoice makes a
--     third, and Stripe retries deliveries on top of that.
--
--     `client_engagement` scores on those rows and the nudge evaluator reads
--     them, so paying an invoice inflated a client's engagement several-fold
--     and suppressed the very at-risk nudge meant to flag them going quiet.
--     That is the failure 0010 closed when a *client* forged events; this one
--     the webhook did to itself.
--
--  B. Stripe does not guarantee delivery order. An `invoice.updated` arriving
--     after `invoice.paid` overwrote the row with the older state, so an
--     invoice could read `open` after it had been paid.
-- ════════════════════════════════════════════════════════════════════════

-- ─── A. One invoice_paid per invoice ────────────────────────────────────

-- Clear the duplicates already recorded, keeping the earliest of each set.
delete from public.activity_events a
using public.activity_events b
where a.event_type = 'invoice_paid'
  and b.event_type = 'invoice_paid'
  and a.client_id is not distinct from b.client_id
  and a.metadata->>'stripe_invoice_id' is not null
  and a.metadata->>'stripe_invoice_id' = b.metadata->>'stripe_invoice_id'
  and (a.created_at, a.id) > (b.created_at, b.id);

-- Enforced by the database, not by the handler: two webhook deliveries can
-- race, and a check-then-insert in application code would still let both
-- through. Rows without a stripe id (none today) stay unconstrained, since
-- NULLs are distinct in a unique index.
create unique index if not exists activity_invoice_paid_once
  on public.activity_events (client_id, (metadata->>'stripe_invoice_id'))
  where event_type = 'invoice_paid';

/**
 * The only way the webhook records a payment.
 *
 * SECURITY DEFINER so the conflict target — a partial index — can be spelled
 * out properly, which PostgREST's `on_conflict` cannot express from the
 * client side.
 */
create or replace function public.log_invoice_paid(
  p_client_id          uuid,
  p_stripe_invoice_id  text,
  p_amount             int
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.activity_events (client_id, event_type, metadata)
  values (
    p_client_id,
    'invoice_paid',
    jsonb_build_object('stripe_invoice_id', p_stripe_invoice_id, 'amount', p_amount)
  )
  on conflict (client_id, (metadata->>'stripe_invoice_id'))
    where event_type = 'invoice_paid'
  do nothing;
end;
$$;

revoke all on function public.log_invoice_paid(uuid, text, int) from public;
grant execute on function public.log_invoice_paid(uuid, text, int) to service_role;

-- ─── B. Ignore events that arrive out of order ──────────────────────────

alter table public.invoices
  add column if not exists last_event_at timestamptz;
alter table public.subscriptions
  add column if not exists last_event_at timestamptz;

/**
 * Upsert an invoice, unless a newer Stripe event has already been applied.
 *
 * `p_event_at` is the webhook event's own `created` timestamp — the only
 * ordering Stripe actually gives us. A delivery older than the last one
 * applied is dropped rather than allowed to regress the row.
 */
create or replace function public.sync_stripe_invoice(
  p_client_id  uuid,
  p_stripe_id  text,
  p_event_at   timestamptz,
  p_fields     jsonb
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.invoices (
    client_id, stripe_invoice_id, number, description, amount, amount_paid,
    currency, status, due_date, paid_at, hosted_invoice_url, last_event_at
  )
  values (
    p_client_id,
    p_stripe_id,
    nullif(p_fields->>'number', ''),
    nullif(p_fields->>'description', ''),
    coalesce((p_fields->>'amount')::int, 0),
    coalesce((p_fields->>'amount_paid')::int, 0),
    coalesce(nullif(p_fields->>'currency', ''), 'gbp'),
    coalesce(nullif(p_fields->>'status', ''), 'open'),
    (p_fields->>'due_date')::timestamptz,
    (p_fields->>'paid_at')::timestamptz,
    nullif(p_fields->>'hosted_invoice_url', ''),
    p_event_at
  )
  on conflict (stripe_invoice_id) do update
  set number             = excluded.number,
      description        = excluded.description,
      amount             = excluded.amount,
      amount_paid        = excluded.amount_paid,
      currency           = excluded.currency,
      status             = excluded.status,
      due_date           = excluded.due_date,
      paid_at            = excluded.paid_at,
      hosted_invoice_url = excluded.hosted_invoice_url,
      last_event_at      = excluded.last_event_at
  where public.invoices.last_event_at is null
     or excluded.last_event_at is null
     or excluded.last_event_at >= public.invoices.last_event_at;
end;
$$;

/** As above, for subscriptions. */
create or replace function public.sync_stripe_subscription(
  p_client_id  uuid,
  p_stripe_id  text,
  p_event_at   timestamptz,
  p_fields     jsonb
)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.subscriptions (
    client_id, stripe_subscription_id, plan, status, amount, currency,
    current_period_end, cancel_at_period_end, last_event_at
  )
  values (
    p_client_id,
    p_stripe_id,
    nullif(p_fields->>'plan', ''),
    coalesce(nullif(p_fields->>'status', ''), 'active'),
    (p_fields->>'amount')::int,
    coalesce(nullif(p_fields->>'currency', ''), 'gbp'),
    (p_fields->>'current_period_end')::timestamptz,
    coalesce((p_fields->>'cancel_at_period_end')::boolean, false),
    p_event_at
  )
  on conflict (stripe_subscription_id) do update
  set plan                 = excluded.plan,
      status               = excluded.status,
      amount               = excluded.amount,
      currency             = excluded.currency,
      current_period_end   = excluded.current_period_end,
      cancel_at_period_end = excluded.cancel_at_period_end,
      last_event_at        = excluded.last_event_at
  where public.subscriptions.last_event_at is null
     or excluded.last_event_at is null
     or excluded.last_event_at >= public.subscriptions.last_event_at;
end;
$$;

revoke all on function public.sync_stripe_invoice(uuid, text, timestamptz, jsonb) from public;
revoke all on function public.sync_stripe_subscription(uuid, text, timestamptz, jsonb) from public;
grant execute on function public.sync_stripe_invoice(uuid, text, timestamptz, jsonb) to service_role;
grant execute on function public.sync_stripe_subscription(uuid, text, timestamptz, jsonb) to service_role;


-- ══════════════════════════════════════════════════════════════════════
--  0015_booking_rules_and_attachments.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 15 — Booking rules, and limits on the attachments bucket
--
--  `request_booking` validated exactly one thing: that the end was after the
--  start. So a client could book last Tuesday, book 3am on a Sunday, or take
--  a slot another client already held. The availability windows an admin
--  sets in /admin/settings were decorative — nothing ever read them.
--
--  The attachments bucket had no size limit, no type restriction, and no
--  DELETE policy: a file could never be removed, by anyone, including an
--  admin.
-- ════════════════════════════════════════════════════════════════════════

-- ─── Booking validation ─────────────────────────────────────────────────

/**
 * Shared by request and reschedule.
 *
 * TIME ZONE: `availability_windows` stores a bare `time` with no zone, and
 * bookings are `timestamptz`, so the comparison has to pick one. It uses UTC.
 * If the studio ever operates from a zone with daylight saving, the windows
 * shift by an hour against local time twice a year — the fix then is a zone
 * column on the window, not arithmetic here.
 *
 * Admins are exempt from all of it: the console is for fixing things, which
 * includes recording a session that happened yesterday or falls outside the
 * published hours.
 */
create or replace function public.assert_bookable(
  p_start   timestamptz,
  p_end     timestamptz,
  p_exclude uuid default null
)
returns void
language plpgsql stable security definer set search_path = public
as $$
declare
  v_weekday int;
  v_from    time;
  v_to      time;
begin
  if p_end <= p_start then
    raise exception 'end must be after start';
  end if;

  if public.is_admin() then
    return;
  end if;

  if p_start < now() then
    raise exception 'that time has already passed';
  end if;

  -- Availability, but only once some has been published. With no windows
  -- configured the admin UI tells you clients can request any time, and this
  -- keeps that promise.
  if exists (select 1 from public.availability_windows where active) then
    v_weekday := extract(dow from (p_start at time zone 'UTC'))::int;
    v_from    := (p_start at time zone 'UTC')::time;
    v_to      := (p_end   at time zone 'UTC')::time;

    -- A window cannot span midnight (end_time > start_time is CHECKed), so a
    -- booking that wraps past midnight can never sit inside one.
    if (p_end at time zone 'UTC')::date <> (p_start at time zone 'UTC')::date
       or not exists (
         select 1 from public.availability_windows w
         where w.active
           and w.weekday = v_weekday
           and w.start_time <= v_from
           and w.end_time   >= v_to
       )
    then
      raise exception 'that time is outside the available hours';
    end if;
  end if;

  -- One studio, one person: a slot already spoken for is not available, even
  -- if the holder is still only `requested`.
  if exists (
    select 1 from public.bookings b
    where b.status in ('requested', 'confirmed')
      and (p_exclude is null or b.id <> p_exclude)
      and b.start_time < p_end
      and b.end_time   > p_start
  ) then
    raise exception 'that slot is already taken';
  end if;
end;
$$;

grant execute on function public.assert_bookable(timestamptz, timestamptz, uuid) to authenticated;

create or replace function public.request_booking(
  p_service_type text,
  p_start        timestamptz,
  p_end          timestamptz,
  p_notes        text default null,
  p_client_id    uuid default null
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
  v_id     uuid;
begin
  v_client := coalesce(p_client_id, public.current_client_id());
  if v_client is null then
    raise exception 'no client context';
  end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;

  perform public.assert_bookable(p_start, p_end);

  insert into public.bookings (client_id, service_type, start_time, end_time, notes, requested_by)
  values (v_client, p_service_type, p_start, p_end, p_notes, auth.uid())
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.reschedule_booking(
  p_id    uuid,
  p_start timestamptz,
  p_end   timestamptz
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_client uuid;
begin
  select client_id into v_client from public.bookings where id = p_id;
  if v_client is null then raise exception 'booking not found'; end if;
  if not (public.is_admin() or v_client = public.current_client_id()) then
    raise exception 'not authorised';
  end if;

  -- Excluded from the overlap check, or moving a booking by ten minutes
  -- would collide with itself.
  perform public.assert_bookable(p_start, p_end, p_id);

  update public.bookings
     set start_time = p_start, end_time = p_end, status = 'requested', decline_reason = null
   where id = p_id and status in ('requested', 'confirmed');
end;
$$;

-- ─── Attachments bucket ─────────────────────────────────────────────────

-- 25 MB, and formats that belong in a client thread. Enforced by storage
-- itself, so it holds however the upload is issued — the browser check in
-- MessageThread is only there to fail politely before the bytes go up.
update storage.buckets
set file_size_limit = 26214400,
    allowed_mime_types = array[
      'image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/svg+xml',
      'application/pdf',
      'text/plain', 'text/csv', 'text/markdown',
      'application/zip',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    ]
where id = 'attachments';

-- 0006 granted SELECT and INSERT and stopped there, so nothing could ever be
-- removed — not a client who attached the wrong file, not an admin, not a
-- cleanup job. Same folder-scoping as the other two.
drop policy if exists "attachments_delete" on storage.objects;
create policy "attachments_delete" on storage.objects
  for delete to authenticated using (
    bucket_id = 'attachments' and (
      public.is_admin()
      or (storage.foldername(name))[1] = public.current_client_id()::text
    )
  );


-- ══════════════════════════════════════════════════════════════════════
--  0016_pitch_view_rate_limit.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 12 — Rate limiting on pitch views
--
--  record_pitch_view() throttles per visitor id, and the visitor id lives in
--  a cookie. That answers "did this person refresh?" but not "is this one
--  person pretending to be a hundred?" — a caller who discards the cookie
--  between requests gets a fresh id each time, and every one of them counts
--  as a new visitor, writes an activity_events row, and moves the number the
--  admin console reports.
--
--  The fix is a second identity the caller doesn't choose: the server passes
--  an opaque fingerprint (an HMAC of the client IP — see
--  lib/os/actions/pitch-view.ts; the raw address is never sent or stored)
--  and a page will accept only so many distinct visitors from one
--  fingerprint per day. Over the cap the view is still recorded as a repeat
--  view, so a genuinely shared office NAT keeps working; it just stops
--  minting new "visitors".
-- ════════════════════════════════════════════════════════════════════════

-- Distinct-visitor budget per fingerprint, per page, per day.
create or replace function public.pitch_view_visitor_cap()
returns int language sql immutable as $$ select 8 $$;

create index if not exists activity_events_pitch_fingerprint_idx
  on public.activity_events (client_id, ((metadata->>'fp')), created_at desc)
  where event_type = 'pitch_viewed';

drop function if exists public.record_pitch_view(text, text);

create or replace function public.record_pitch_view(
  p_slug        text,
  p_visitor     text,
  p_fingerprint text default null
)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  v_client       uuid;
  v_recent       boolean;
  v_is_new       boolean;
  v_fp_visitors  int := 0;
begin
  if p_visitor is null or length(p_visitor) not between 8 and 64 then
    return false;
  end if;

  -- The fingerprint is minted server-side and is always a fixed-width hex
  -- digest. Anything else is a caller trying its luck; drop it rather than
  -- letting an arbitrary string become a rate-limit bucket of its own.
  if p_fingerprint is not null
     and p_fingerprint !~ '^[0-9a-f]{32}$' then
    p_fingerprint := null;
  end if;

  select c.id into v_client
  from public.clients c
  join public.client_pages p on p.client_id = c.id
  where c.slug = p_slug and p.published = true;

  if v_client is null then
    return false;
  end if;

  -- One view per visitor per 30 minutes, so a refresh isn't a second read.
  select exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'visitor' = p_visitor
      and created_at > now() - interval '30 minutes'
  ) into v_recent;

  if v_recent then
    return false;
  end if;

  -- Has this visitor ever been seen on this page before?
  select not exists (
    select 1 from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'visitor' = p_visitor
  ) into v_is_new;

  -- How many distinct visitors has this fingerprint already produced today?
  if v_is_new and p_fingerprint is not null then
    select count(distinct metadata->>'visitor')
    into v_fp_visitors
    from public.activity_events
    where client_id  = v_client
      and event_type = 'pitch_viewed'
      and metadata->>'fp' = p_fingerprint
      and created_at > now() - interval '1 day';

    -- Over budget: record the read, but don't let it mint a new visitor.
    if v_fp_visitors >= public.pitch_view_visitor_cap() then
      v_is_new := false;
    end if;
  end if;

  insert into public.activity_events (client_id, actor_id, event_type, metadata)
  values (
    v_client,
    null,
    'pitch_viewed',
    jsonb_strip_nulls(
      jsonb_build_object('visitor', p_visitor, 'fp', p_fingerprint)
    )
  );

  update public.client_pages
  set view_count      = view_count + 1,
      visitor_count   = visitor_count + (case when v_is_new then 1 else 0 end),
      first_viewed_at = coalesce(first_viewed_at, now()),
      last_viewed_at  = now()
  where client_id = v_client;

  return true;
end;
$$;

-- Called from a server action, but granted to anon as well: the whole point
-- is counting people who have no account yet.
grant execute on function public.record_pitch_view(text, text, text)
  to anon, authenticated;


-- ══════════════════════════════════════════════════════════════════════
--  0017_contact_submissions.sql
-- ══════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════════
--  Phase 14 — Durable contact submissions
--
--  The studio contact form posted to Netlify Forms and nowhere else. That
--  made a lead's survival depend entirely on one third party being up at the
--  moment somebody clicked Send: if the POST failed the visitor saw
--  "something went wrong", and the enquiry existed nowhere at all. It also
--  meant the only record of who had asked for what lived in a dashboard
--  outside the app, invisible to /admin.
--
--  Submissions now land here first, through a SECURITY DEFINER function so
--  anonymous visitors never touch the table directly. Netlify Forms stays as
--  the notification channel; this is the record.
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.contact_submissions (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  email        text not null,
  company      text,
  project_type text,
  message      text not null,
  -- Which pitch page or campaign the lead came from (?ref= on the studio URL).
  ref          text,
  -- Set once an admin has dealt with it; drives the unread count in /admin.
  handled_at   timestamptz,
  -- Non-null once this submission has been linked to a client record.
  client_id    uuid references public.clients (id) on delete set null,
  created_at   timestamptz not null default now()
);

create index if not exists contact_submissions_time_idx
  on public.contact_submissions (created_at desc);
create index if not exists contact_submissions_unhandled_idx
  on public.contact_submissions (created_at desc)
  where handled_at is null;

alter table public.contact_submissions enable row level security;

-- Admins only. There is no client-facing read path: a submission is a lead,
-- not something the person who sent it comes back to look at.
-- Drop-then-create, like every other policy in this schema: `create policy`
-- has no `if not exists`, so without this the migration is not re-runnable.
drop policy if exists contact_submissions_admin_all on public.contact_submissions;
create policy contact_submissions_admin_all on public.contact_submissions
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

/**
 * Record one submission. Anonymous by design — the whole point is capturing
 * people who have no account.
 *
 * Everything is length-capped here rather than trusted from the caller: this
 * is a public write path, and the only thing standing between it and the
 * table is this function. Returns false rather than raising on bad input, so
 * a malformed post is a quiet no-op instead of a 500 on the contact page.
 */
create or replace function public.submit_contact(
  p_name         text,
  p_email        text,
  p_message      text,
  p_company      text default null,
  p_project_type text default null,
  p_ref          text default null
)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  v_recent int;
begin
  if coalesce(trim(p_name), '') = ''
     or coalesce(trim(p_message), '') = ''
     or p_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    return false;
  end if;

  -- A public insert endpoint needs a ceiling. Same address, same hour: five.
  select count(*) into v_recent
  from public.contact_submissions
  where lower(email) = lower(trim(p_email))
    and created_at > now() - interval '1 hour';

  if v_recent >= 5 then
    return false;
  end if;

  insert into public.contact_submissions
    (name, email, company, project_type, message, ref)
  values (
    left(trim(p_name), 120),
    lower(left(trim(p_email), 200)),
    nullif(left(trim(coalesce(p_company, '')), 160), ''),
    nullif(left(trim(coalesce(p_project_type, '')), 80), ''),
    left(trim(p_message), 5000),
    nullif(left(trim(coalesce(p_ref, '')), 80), '')
  );

  return true;
end;
$$;

grant execute on function
  public.submit_contact(text, text, text, text, text, text)
  to anon, authenticated;

/** Mark a submission dealt with. Admin-only; RLS on the table enforces it. */
create or replace function public.mark_contact_handled(p_id uuid)
returns boolean
language plpgsql security invoker set search_path = public
as $$
begin
  update public.contact_submissions
  set handled_at = now()
  where id = p_id and handled_at is null;
  return found;
end;
$$;

grant execute on function public.mark_contact_handled(uuid) to authenticated;


commit;

-- ══════════════════════════════════════════════════════════════════════
--  Verification — what this bundle should have left behind.
--  Every row below should read 'ok'.
-- ══════════════════════════════════════════════════════════════════════
select
  'client_preferences table'                                        as object,
  case when to_regclass('public.client_preferences') is not null
       then 'ok' else 'MISSING' end                                 as status
union all select 'preferences row per client',
  case when (select count(*) from public.clients)
          = (select count(*) from public.client_preferences)
       then 'ok' else 'MISMATCH' end
union all select 'invoices.last_event_at column',
  case when exists (select 1 from information_schema.columns
                    where table_schema='public' and table_name='invoices'
                      and column_name='last_event_at')
       then 'ok' else 'MISSING' end
union all select 'one invoice_paid per invoice (unique index)',
  case when exists (select 1 from pg_indexes
                    where schemaname='public' and indexname='activity_invoice_paid_once')
       then 'ok' else 'MISSING' end
union all select 'attachments size + type limits',
  case when exists (select 1 from storage.buckets
                    where id='attachments' and file_size_limit is not null
                      and allowed_mime_types is not null)
       then 'ok' else 'MISSING' end
union all select 'attachments delete policy',
  case when exists (select 1 from pg_policies
                    where schemaname='storage' and tablename='objects'
                      and policyname='attachments_delete')
       then 'ok' else 'MISSING' end
union all select 'functions the app calls',
  case when (select count(*) from pg_proc p
             join pg_namespace n on n.oid = p.pronamespace
             where n.nspname='public' and p.proname in (
               'update_my_profile','update_my_preferences',
               'analytics_revenue','analytics_activity','analytics_event_mix',
               'analytics_top_clients','analytics_active_clients',
               'clients_idle_since','log_invoice_paid',
               'sync_stripe_invoice','sync_stripe_subscription','assert_bookable'
             )) = 12
       then 'ok' else 'MISSING ONE OR MORE' end;
